/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Vistas_Unidad1;

import javax.swing.JButton;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_LeccionFONOLOGIA extends javax.swing.JPanel {
private String rutaAudio;
    /**
     * Creates new form Vista_LeccionFONOLOGIA
     */
    public Vista_LeccionFONOLOGIA() {
        initComponents();
        
    }

   


    // ✅ Estos son los métodos para guardar y recuperar la ruta del audio:
    public void setRutaAudio(String rutaAudio) {
        this.rutaAudio = rutaAudio;
    }

    public String getRutaAudio() {
        return rutaAudio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedorF = new javax.swing.JPanel();
        jPanelPag1F = new javax.swing.JPanel();
        jPanelVideo = new javax.swing.JPanel();
        jButtonCompletarLeccionFonologia = new javax.swing.JButton();
        jSliderTiempoVideo = new javax.swing.JSlider();
        jLabelTiempoVP = new javax.swing.JLabel();
        jButtonPlay = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jSliderSubirBajarVolumen = new javax.swing.JSlider();
        jButtonSonido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setPreferredSize(new java.awt.Dimension(1190, 660));

        jPanelContenedorF.setLayout(new java.awt.CardLayout());

        jPanelPag1F.setMaximumSize(new java.awt.Dimension(1190, 660));
        jPanelPag1F.setMinimumSize(new java.awt.Dimension(1190, 660));
        jPanelPag1F.setPreferredSize(new java.awt.Dimension(1190, 660));
        jPanelPag1F.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanelVideoLayout = new javax.swing.GroupLayout(jPanelVideo);
        jPanelVideo.setLayout(jPanelVideoLayout);
        jPanelVideoLayout.setHorizontalGroup(
            jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        jPanelVideoLayout.setVerticalGroup(
            jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanelPag1F.add(jPanelVideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 1040, 480));

        jButtonCompletarLeccionFonologia.setBackground(new java.awt.Color(255, 153, 51));
        jButtonCompletarLeccionFonologia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCompletarLeccionFonologia.setText("COMPLETAR");
        jPanelPag1F.add(jButtonCompletarLeccionFonologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 600, 240, 50));
        jPanelPag1F.add(jSliderTiempoVideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 990, -1));

        jLabelTiempoVP.setText("jLabel2");
        jPanelPag1F.add(jLabelTiempoVP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 560, -1, 20));

        jButtonPlay.setBackground(new java.awt.Color(255, 153, 51));
        jButtonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad1/Play.png"))); // NOI18N
        jPanelPag1F.add(jButtonPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 50, 40));

        jButtonStop.setBackground(new java.awt.Color(255, 153, 51));
        jButtonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad1/Stop.png"))); // NOI18N
        jPanelPag1F.add(jButtonStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 50, 40));

        jSliderSubirBajarVolumen.setOrientation(javax.swing.JSlider.VERTICAL);
        jPanelPag1F.add(jSliderSubirBajarVolumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 70, -1, 420));

        jButtonSonido.setBackground(new java.awt.Color(255, 153, 51));
        jButtonSonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad1/volumen.png"))); // NOI18N
        jPanelPag1F.add(jButtonSonido, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 510, 50, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("FONOLOGIA KICHWA");
        jPanelPag1F.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 250, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad1/Fondo1U1.jpg"))); // NOI18N
        jPanelPag1F.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelContenedorF.add(jPanelPag1F, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelContenedorF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelContenedorF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

//Componentes del editor visual de netbeans de la Vista leccion Fonologia
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonCompletarLeccionFonologia;
    public javax.swing.JButton jButtonPlay;
    public javax.swing.JButton jButtonSonido;
    public javax.swing.JButton jButtonStop;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabelTiempoVP;
    public javax.swing.JPanel jPanelContenedorF;
    public javax.swing.JPanel jPanelPag1F;
    public javax.swing.JPanel jPanelVideo;
    public javax.swing.JSlider jSliderSubirBajarVolumen;
    public javax.swing.JSlider jSliderTiempoVideo;
    // End of variables declaration//GEN-END:variables
}
