/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Vistas_Unidad1;

import javax.accessibility.AccessibleContext;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.event.EventListenerList;
import javax.swing.plaf.ComponentUI;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_EvaluacionU1 extends javax.swing.JPanel {

    /**
     * Creates new form Vista_EvaluacionU1
     */
    public Vista_EvaluacionU1() {
        initComponents();
       

    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public JButton getjButtonFINALIZARUNIDAD() {
        return jButtonFINALIZARUNIDAD;
    }

    public void setjButtonFINALIZARUNIDAD(JButton jButtonFINALIZARUNIDAD) {
        this.jButtonFINALIZARUNIDAD = jButtonFINALIZARUNIDAD;
    }

    public JButton getjButtonSIGUIENTE() {
        return jButtonSIGUIENTE;
    }

    public void setjButtonSIGUIENTE(JButton jButtonSIGUIENTE) {
        this.jButtonSIGUIENTE = jButtonSIGUIENTE;
    }

    public JLabel getjLabelImagen() {
        return jLabelImagen;
    }

    public void setjLabelImagen(JLabel jLabelImagen) {
        this.jLabelImagen = jLabelImagen;
    }

    public JLabel getjLabelProgresoDePregunta() {
        return jLabelProgresoDePregunta;
    }

    public void setjLabelProgresoDePregunta(JLabel jLabelProgresoDePregunta) {
        this.jLabelProgresoDePregunta = jLabelProgresoDePregunta;
    }

    public JRadioButton getjRadioButtonA() {
        return jRadioButtonA;
    }

    public void setjRadioButtonA(JRadioButton jRadioButtonA) {
        this.jRadioButtonA = jRadioButtonA;
    }

    public JRadioButton getjRadioButtonB() {
        return jRadioButtonB;
    }

    public void setjRadioButtonB(JRadioButton jRadioButtonB) {
        this.jRadioButtonB = jRadioButtonB;
    }

    public JRadioButton getjRadioButtonC() {
        return jRadioButtonC;
    }

    public void setjRadioButtonC(JRadioButton jRadioButtonC) {
        this.jRadioButtonC = jRadioButtonC;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextArea getjTextAreaPregunta() {
        return jTextAreaPregunta;
    }

    public void setjTextAreaPregunta(JTextArea jTextAreaPregunta) {
        this.jTextAreaPregunta = jTextAreaPregunta;
    }

    public ComponentUI getUi() {
        return ui;
    }

    public void setUi(ComponentUI ui) {
        this.ui = ui;
    }

    public EventListenerList getListenerList() {
        return listenerList;
    }

    public void setListenerList(EventListenerList listenerList) {
        this.listenerList = listenerList;
    }

    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }

    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.accessibleContext = accessibleContext;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPregunta = new javax.swing.JTextArea();
        jRadioButtonA = new javax.swing.JRadioButton();
        jRadioButtonB = new javax.swing.JRadioButton();
        jRadioButtonC = new javax.swing.JRadioButton();
        jLabelImagen = new javax.swing.JLabel();
        jButtonSIGUIENTE = new javax.swing.JButton();
        jButtonFINALIZARUNIDAD = new javax.swing.JButton();
        jLabelProgresoDePregunta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setPreferredSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setToolTipText("");

        jTextAreaPregunta.setColumns(20);
        jTextAreaPregunta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextAreaPregunta.setRows(5);
        jTextAreaPregunta.setToolTipText("");
        jTextAreaPregunta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextAreaPregunta);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 627, 30));

        buttonGroup1.add(jRadioButtonA);
        jRadioButtonA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButtonA.setText("jRadioButton1");
        add(jRadioButtonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, -1, -1));

        buttonGroup1.add(jRadioButtonB);
        jRadioButtonB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButtonB.setText("jRadioButton2");
        add(jRadioButtonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, -1, -1));

        buttonGroup1.add(jRadioButtonC);
        jRadioButtonC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButtonC.setText("jRadioButton3");
        add(jRadioButtonC, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, -1, -1));

        jLabelImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelImagen.setPreferredSize(new java.awt.Dimension(200, 200));
        add(jLabelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 280, 260));

        jButtonSIGUIENTE.setBackground(new java.awt.Color(255, 153, 51));
        jButtonSIGUIENTE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSIGUIENTE.setText("SIGUIENTE");
        jButtonSIGUIENTE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jButtonSIGUIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 590, 110, 48));

        jButtonFINALIZARUNIDAD.setBackground(new java.awt.Color(255, 153, 51));
        jButtonFINALIZARUNIDAD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonFINALIZARUNIDAD.setText("FINALIZAR");
        add(jButtonFINALIZARUNIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1006, 588, 137, 48));

        jLabelProgresoDePregunta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelProgresoDePregunta.setText("jLabel2");
        add(jLabelProgresoDePregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 230, 43));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("RESPONDE LAS 10 PREGUNTAS CORRECTAMENTE");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 870, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad1/Fondo1U1.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 660));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton jButtonFINALIZARUNIDAD;
    public javax.swing.JButton jButtonSIGUIENTE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabelImagen;
    public javax.swing.JLabel jLabelProgresoDePregunta;
    public javax.swing.JRadioButton jRadioButtonA;
    public javax.swing.JRadioButton jRadioButtonB;
    public javax.swing.JRadioButton jRadioButtonC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaPregunta;
    // End of variables declaration//GEN-END:variables
}
