/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Vistas_Unidad1;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_Actividad1U1 extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad1U1
     */
    public Vista_Actividad1U1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupOpcionesP1 = new javax.swing.ButtonGroup();
        buttonGroupOpcionesP2 = new javax.swing.ButtonGroup();
        buttonGroupOpcionesP3 = new javax.swing.ButtonGroup();
        jPanelContenedor = new javax.swing.JPanel();
        jPanelAPag1 = new javax.swing.JPanel();
        jPanelPregunta1 = new javax.swing.JPanel();
        jLabelPregunta1 = new javax.swing.JLabel();
        jRadioButtonOpcion1P1 = new javax.swing.JRadioButton();
        jRadioButtonOpcion2P1 = new javax.swing.JRadioButton();
        jRadioButtonOpcion3P1 = new javax.swing.JRadioButton();
        jPanelPregunta3 = new javax.swing.JPanel();
        jRadioButtonOpcion1P3 = new javax.swing.JRadioButton();
        jRadioButtonOpcion2P3 = new javax.swing.JRadioButton();
        jRadioButtonOpcion3P3 = new javax.swing.JRadioButton();
        jLabelPregunta3 = new javax.swing.JLabel();
        jPanelPregunta2 = new javax.swing.JPanel();
        jRadioButtonOpcion1P2 = new javax.swing.JRadioButton();
        jRadioButtonOpcion2P2 = new javax.swing.JRadioButton();
        jRadioButtonOpcion3P2 = new javax.swing.JRadioButton();
        jLabelPregunta2 = new javax.swing.JLabel();
        jButtonCOMPLETOACTV1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setPreferredSize(new java.awt.Dimension(1190, 660));

        jPanelContenedor.setMaximumSize(new java.awt.Dimension(1190, 660));
        jPanelContenedor.setMinimumSize(new java.awt.Dimension(1190, 660));
        jPanelContenedor.setName(""); // NOI18N
        jPanelContenedor.setPreferredSize(new java.awt.Dimension(1190, 660));
        jPanelContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelAPag1.setBackground(new java.awt.Color(255, 153, 102));
        jPanelAPag1.setFocusCycleRoot(true);
        jPanelAPag1.setMaximumSize(new java.awt.Dimension(1190, 660));
        jPanelAPag1.setMinimumSize(new java.awt.Dimension(1190, 660));
        jPanelAPag1.setPreferredSize(new java.awt.Dimension(1190, 660));
        jPanelAPag1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPregunta1.setBackground(new java.awt.Color(204, 255, 204));
        jPanelPregunta1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelPregunta1.setAlignmentX(0.3F);
        jPanelPregunta1.setMaximumSize(new java.awt.Dimension(500, 200));
        jPanelPregunta1.setMinimumSize(new java.awt.Dimension(500, 200));
        jPanelPregunta1.setName(""); // NOI18N
        jPanelPregunta1.setPreferredSize(new java.awt.Dimension(500, 200));

        jLabelPregunta1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPregunta1.setText("jLabel1");

        buttonGroupOpcionesP1.add(jRadioButtonOpcion1P1);
        jRadioButtonOpcion1P1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButtonOpcion1P1.setText("jRadioButton1");
        jRadioButtonOpcion1P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOpcion1P1ActionPerformed(evt);
            }
        });

        buttonGroupOpcionesP1.add(jRadioButtonOpcion2P1);
        jRadioButtonOpcion2P1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButtonOpcion2P1.setText("jRadioButton2");

        buttonGroupOpcionesP1.add(jRadioButtonOpcion3P1);
        jRadioButtonOpcion3P1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButtonOpcion3P1.setText("jRadioButton3");

        javax.swing.GroupLayout jPanelPregunta1Layout = new javax.swing.GroupLayout(jPanelPregunta1);
        jPanelPregunta1.setLayout(jPanelPregunta1Layout);
        jPanelPregunta1Layout.setHorizontalGroup(
            jPanelPregunta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPregunta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPregunta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPregunta1Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(jPanelPregunta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jRadioButtonOpcion2P1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonOpcion1P1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonOpcion3P1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );
        jPanelPregunta1Layout.setVerticalGroup(
            jPanelPregunta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPregunta1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelPregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonOpcion1P1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonOpcion2P1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonOpcion3P1)
                .addContainerGap())
        );

        jPanelAPag1.add(jPanelPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 460, -1));

        jPanelPregunta3.setBackground(new java.awt.Color(204, 255, 204));
        jPanelPregunta3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelPregunta3.setAlignmentX(0.3F);
        jPanelPregunta3.setMaximumSize(new java.awt.Dimension(500, 200));
        jPanelPregunta3.setMinimumSize(new java.awt.Dimension(500, 200));
        jPanelPregunta3.setName(""); // NOI18N
        jPanelPregunta3.setPreferredSize(new java.awt.Dimension(500, 200));

        buttonGroupOpcionesP3.add(jRadioButtonOpcion1P3);
        jRadioButtonOpcion1P3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButtonOpcion1P3.setText("jRadioButton1");
        jRadioButtonOpcion1P3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOpcion1P3ActionPerformed(evt);
            }
        });

        buttonGroupOpcionesP3.add(jRadioButtonOpcion2P3);
        jRadioButtonOpcion2P3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButtonOpcion2P3.setText("jRadioButton2");
        jRadioButtonOpcion2P3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOpcion2P3ActionPerformed(evt);
            }
        });

        buttonGroupOpcionesP3.add(jRadioButtonOpcion3P3);
        jRadioButtonOpcion3P3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButtonOpcion3P3.setText("jRadioButton3");

        jLabelPregunta3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPregunta3.setText("jLabel1");

        javax.swing.GroupLayout jPanelPregunta3Layout = new javax.swing.GroupLayout(jPanelPregunta3);
        jPanelPregunta3.setLayout(jPanelPregunta3Layout);
        jPanelPregunta3Layout.setHorizontalGroup(
            jPanelPregunta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPregunta3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelPregunta3Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanelPregunta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jRadioButtonOpcion2P3)
                    .addComponent(jRadioButtonOpcion1P3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonOpcion3P3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jPanelPregunta3Layout.setVerticalGroup(
            jPanelPregunta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPregunta3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelPregunta3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonOpcion1P3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonOpcion3P3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonOpcion2P3)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanelAPag1.add(jPanelPregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 450, -1));

        jPanelPregunta2.setBackground(new java.awt.Color(204, 255, 204));
        jPanelPregunta2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelPregunta2.setAlignmentX(0.3F);
        jPanelPregunta2.setMaximumSize(new java.awt.Dimension(500, 200));
        jPanelPregunta2.setMinimumSize(new java.awt.Dimension(500, 200));
        jPanelPregunta2.setName(""); // NOI18N
        jPanelPregunta2.setPreferredSize(new java.awt.Dimension(500, 200));

        buttonGroupOpcionesP2.add(jRadioButtonOpcion1P2);
        jRadioButtonOpcion1P2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButtonOpcion1P2.setText("jRadioButton1");
        jRadioButtonOpcion1P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOpcion1P2ActionPerformed(evt);
            }
        });

        buttonGroupOpcionesP2.add(jRadioButtonOpcion2P2);
        jRadioButtonOpcion2P2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButtonOpcion2P2.setText("jRadioButton2");

        buttonGroupOpcionesP2.add(jRadioButtonOpcion3P2);
        jRadioButtonOpcion3P2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jRadioButtonOpcion3P2.setText("jRadioButton3");

        jLabelPregunta2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPregunta2.setText("jLabel1");

        javax.swing.GroupLayout jPanelPregunta2Layout = new javax.swing.GroupLayout(jPanelPregunta2);
        jPanelPregunta2.setLayout(jPanelPregunta2Layout);
        jPanelPregunta2Layout.setHorizontalGroup(
            jPanelPregunta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPregunta2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPregunta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPregunta2Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(jPanelPregunta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jRadioButtonOpcion2P2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonOpcion3P2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonOpcion1P2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
        jPanelPregunta2Layout.setVerticalGroup(
            jPanelPregunta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPregunta2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonOpcion1P2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonOpcion2P2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonOpcion3P2)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanelAPag1.add(jPanelPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 450, -1));

        jButtonCOMPLETOACTV1.setBackground(new java.awt.Color(255, 153, 51));
        jButtonCOMPLETOACTV1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonCOMPLETOACTV1.setText("Terminar");
        jButtonCOMPLETOACTV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCOMPLETOACTV1ActionPerformed(evt);
            }
        });
        jPanelAPag1.add(jButtonCOMPLETOACTV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 540, 150, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad1/Fondo1U1.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanelAPag1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 660));

        jPanelContenedor.add(jPanelAPag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("                               Responde las Preguntas Correctamente para pasar a la siguiente Actividad.");
        jLabel1.setToolTipText("    ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonOpcion1P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOpcion1P1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonOpcion1P1ActionPerformed

    private void jRadioButtonOpcion1P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOpcion1P2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonOpcion1P2ActionPerformed

    private void jRadioButtonOpcion1P3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOpcion1P3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonOpcion1P3ActionPerformed

    private void jRadioButtonOpcion2P3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOpcion2P3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonOpcion2P3ActionPerformed

    private void jButtonCOMPLETOACTV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCOMPLETOACTV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCOMPLETOACTV1ActionPerformed

//Variables de la Vista_ActividadU1
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroupOpcionesP1;
    public javax.swing.ButtonGroup buttonGroupOpcionesP2;
    public javax.swing.ButtonGroup buttonGroupOpcionesP3;
    public javax.swing.JButton jButtonCOMPLETOACTV1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabelPregunta1;
    public javax.swing.JLabel jLabelPregunta2;
    public javax.swing.JLabel jLabelPregunta3;
    public javax.swing.JPanel jPanelAPag1;
    public javax.swing.JPanel jPanelContenedor;
    public javax.swing.JPanel jPanelPregunta1;
    public javax.swing.JPanel jPanelPregunta2;
    public javax.swing.JPanel jPanelPregunta3;
    public javax.swing.JRadioButton jRadioButtonOpcion1P1;
    public javax.swing.JRadioButton jRadioButtonOpcion1P2;
    public javax.swing.JRadioButton jRadioButtonOpcion1P3;
    public javax.swing.JRadioButton jRadioButtonOpcion2P1;
    public javax.swing.JRadioButton jRadioButtonOpcion2P2;
    public javax.swing.JRadioButton jRadioButtonOpcion2P3;
    public javax.swing.JRadioButton jRadioButtonOpcion3P1;
    public javax.swing.JRadioButton jRadioButtonOpcion3P2;
    public javax.swing.JRadioButton jRadioButtonOpcion3P3;
    // End of variables declaration//GEN-END:variables
}
