/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Vistas_Unidad1;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_LeccionPRONOMBRES extends javax.swing.JPanel {

    /**
     * Creates new form Vista_LeccionPRONOMBRES
     */
    public Vista_LeccionPRONOMBRES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedorP = new javax.swing.JPanel();
        jPanelPag1P = new javax.swing.JPanel();
        jPanelVideoP = new javax.swing.JPanel();
        jLabelTiempoVP = new javax.swing.JLabel();
        jButtonPlay = new javax.swing.JButton();
        jButtonPausa = new javax.swing.JButton();
        jSliderProgresoVideoP = new javax.swing.JSlider();
        jSliderSubirBajarVolumenP = new javax.swing.JSlider();
        jButtonSiguientePag2P = new javax.swing.JButton();
        jButtonVolumenP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelPag2P = new javax.swing.JPanel();
        jLabelImagen1Pronombres = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTexto1P = new javax.swing.JTextArea();
        jButtonCOMPLETOPRONOMBRES = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setPreferredSize(new java.awt.Dimension(1190, 660));

        jPanelContenedorP.setMaximumSize(new java.awt.Dimension(1190, 660));
        jPanelContenedorP.setPreferredSize(new java.awt.Dimension(1190, 660));
        jPanelContenedorP.setLayout(new java.awt.CardLayout());

        jPanelPag1P.setMaximumSize(new java.awt.Dimension(1190, 660));
        jPanelPag1P.setMinimumSize(new java.awt.Dimension(1190, 660));
        jPanelPag1P.setPreferredSize(new java.awt.Dimension(1190, 660));
        jPanelPag1P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelVideoP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelVideoP.setPreferredSize(new java.awt.Dimension(1040, 480));

        javax.swing.GroupLayout jPanelVideoPLayout = new javax.swing.GroupLayout(jPanelVideoP);
        jPanelVideoP.setLayout(jPanelVideoPLayout);
        jPanelVideoPLayout.setHorizontalGroup(
            jPanelVideoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );
        jPanelVideoPLayout.setVerticalGroup(
            jPanelVideoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        jPanelPag1P.add(jPanelVideoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 370, -1));

        jLabelTiempoVP.setText("jLabel2");
        jPanelPag1P.add(jLabelTiempoVP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 560, -1, -1));

        jButtonPlay.setBackground(new java.awt.Color(255, 153, 51));
        jButtonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad1/Play.png"))); // NOI18N
        jPanelPag1P.add(jButtonPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 50, 40));

        jButtonPausa.setBackground(new java.awt.Color(255, 153, 51));
        jButtonPausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad1/Stop.png"))); // NOI18N
        jPanelPag1P.add(jButtonPausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 50, 40));
        jPanelPag1P.add(jSliderProgresoVideoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 996, -1));

        jSliderSubirBajarVolumenP.setOrientation(javax.swing.JSlider.VERTICAL);
        jPanelPag1P.add(jSliderSubirBajarVolumenP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1094, 85, -1, 406));

        jButtonSiguientePag2P.setBackground(new java.awt.Color(255, 153, 51));
        jButtonSiguientePag2P.setText("Siguiente Pag");
        jPanelPag1P.add(jButtonSiguientePag2P, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 610, 130, 39));

        jButtonVolumenP.setBackground(new java.awt.Color(255, 153, 51));
        jButtonVolumenP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad1/volumen.png"))); // NOI18N
        jPanelPag1P.add(jButtonVolumenP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 500, 50, 40));

        jLabel1.setBackground(new java.awt.Color(255, 153, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("PRONOMBRES EN KICHWA");
        jPanelPag1P.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 240, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad1/Fondo1U1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanelPag1P.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 660));

        jPanelContenedorP.add(jPanelPag1P, "card4");

        jPanelPag2P.setMaximumSize(new java.awt.Dimension(1190, 660));
        jPanelPag2P.setMinimumSize(new java.awt.Dimension(1190, 660));
        jPanelPag2P.setPreferredSize(new java.awt.Dimension(1190, 660));
        jPanelPag2P.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImagen1Pronombres.setText("jLabel2");
        jPanelPag2P.add(jLabelImagen1Pronombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 51, 426, 513));

        jTextAreaTexto1P.setColumns(20);
        jTextAreaTexto1P.setRows(5);
        jScrollPane1.setViewportView(jTextAreaTexto1P);

        jPanelPag2P.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 37, 425, 513));

        jButtonCOMPLETOPRONOMBRES.setText("COMPLETAR");
        jPanelPag2P.add(jButtonCOMPLETOPRONOMBRES, new org.netbeans.lib.awtextra.AbsoluteConstraints(1042, 600, 126, 46));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad1/Fondo1U1.jpg"))); // NOI18N
        jPanelPag2P.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 660));

        jPanelContenedorP.add(jPanelPag2P, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelContenedorP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelContenedorP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

//Componentes del editor visual de netbeans de la Vista leccion Pronombres
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonCOMPLETOPRONOMBRES;
    public javax.swing.JButton jButtonPausa;
    public javax.swing.JButton jButtonPlay;
    public javax.swing.JButton jButtonSiguientePag2P;
    public javax.swing.JButton jButtonVolumenP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabelImagen1Pronombres;
    public javax.swing.JLabel jLabelTiempoVP;
    public javax.swing.JPanel jPanelContenedorP;
    public javax.swing.JPanel jPanelPag1P;
    public javax.swing.JPanel jPanelPag2P;
    public javax.swing.JPanel jPanelVideoP;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSlider jSliderProgresoVideoP;
    public javax.swing.JSlider jSliderSubirBajarVolumenP;
    public javax.swing.JTextArea jTextAreaTexto1P;
    // End of variables declaration//GEN-END:variables
}
