/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Vistas_Unidad1;

import javax.accessibility.AccessibleContext;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.event.EventListenerList;
import javax.swing.plaf.ComponentUI;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_EvaluacionU1 extends javax.swing.JPanel {

    /**
     * Creates new form Vista_EvaluacionU1
     */
    public Vista_EvaluacionU1() {
        initComponents();
       

    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public JButton getjButtonFINALIZARUNIDAD() {
        return jButtonFINALIZARUNIDAD;
    }

    public void setjButtonFINALIZARUNIDAD(JButton jButtonFINALIZARUNIDAD) {
        this.jButtonFINALIZARUNIDAD = jButtonFINALIZARUNIDAD;
    }

    public JButton getjButtonSIGUIENTE() {
        return jButtonSIGUIENTE;
    }

    public void setjButtonSIGUIENTE(JButton jButtonSIGUIENTE) {
        this.jButtonSIGUIENTE = jButtonSIGUIENTE;
    }

    public JLabel getjLabelImagen() {
        return jLabelImagen;
    }

    public void setjLabelImagen(JLabel jLabelImagen) {
        this.jLabelImagen = jLabelImagen;
    }

    public JLabel getjLabelProgresoDePregunta() {
        return jLabelProgresoDePregunta;
    }

    public void setjLabelProgresoDePregunta(JLabel jLabelProgresoDePregunta) {
        this.jLabelProgresoDePregunta = jLabelProgresoDePregunta;
    }

    public JRadioButton getjRadioButtonA() {
        return jRadioButtonA;
    }

    public void setjRadioButtonA(JRadioButton jRadioButtonA) {
        this.jRadioButtonA = jRadioButtonA;
    }

    public JRadioButton getjRadioButtonB() {
        return jRadioButtonB;
    }

    public void setjRadioButtonB(JRadioButton jRadioButtonB) {
        this.jRadioButtonB = jRadioButtonB;
    }

    public JRadioButton getjRadioButtonC() {
        return jRadioButtonC;
    }

    public void setjRadioButtonC(JRadioButton jRadioButtonC) {
        this.jRadioButtonC = jRadioButtonC;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextArea getjTextAreaPregunta() {
        return jTextAreaPregunta;
    }

    public void setjTextAreaPregunta(JTextArea jTextAreaPregunta) {
        this.jTextAreaPregunta = jTextAreaPregunta;
    }

    public ComponentUI getUi() {
        return ui;
    }

    public void setUi(ComponentUI ui) {
        this.ui = ui;
    }

    public EventListenerList getListenerList() {
        return listenerList;
    }

    public void setListenerList(EventListenerList listenerList) {
        this.listenerList = listenerList;
    }

    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }

    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.accessibleContext = accessibleContext;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPregunta = new javax.swing.JTextArea();
        jRadioButtonA = new javax.swing.JRadioButton();
        jRadioButtonB = new javax.swing.JRadioButton();
        jRadioButtonC = new javax.swing.JRadioButton();
        jLabelImagen = new javax.swing.JLabel();
        jButtonSIGUIENTE = new javax.swing.JButton();
        jButtonFINALIZARUNIDAD = new javax.swing.JButton();
        jLabelProgresoDePregunta = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setPreferredSize(new java.awt.Dimension(1190, 660));

        jTextAreaPregunta.setColumns(20);
        jTextAreaPregunta.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPregunta);

        buttonGroup1.add(jRadioButtonA);
        jRadioButtonA.setText("jRadioButton1");

        buttonGroup1.add(jRadioButtonB);
        jRadioButtonB.setText("jRadioButton2");

        buttonGroup1.add(jRadioButtonC);
        jRadioButtonC.setText("jRadioButton3");

        jLabelImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelImagen.setPreferredSize(new java.awt.Dimension(200, 200));

        jButtonSIGUIENTE.setText("SIGUIENTE");

        jButtonFINALIZARUNIDAD.setText("FINALIZAR");

        jLabelProgresoDePregunta.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(439, 439, 439)
                        .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelProgresoDePregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButtonB)
                            .addComponent(jRadioButtonA)
                            .addComponent(jRadioButtonC)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(301, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSIGUIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jButtonFINALIZARUNIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProgresoDePregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonA)
                .addGap(29, 29, 29)
                .addComponent(jRadioButtonB)
                .addGap(31, 31, 31)
                .addComponent(jRadioButtonC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSIGUIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFINALIZARUNIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton jButtonFINALIZARUNIDAD;
    public javax.swing.JButton jButtonSIGUIENTE;
    public javax.swing.JLabel jLabelImagen;
    public javax.swing.JLabel jLabelProgresoDePregunta;
    public javax.swing.JRadioButton jRadioButtonA;
    public javax.swing.JRadioButton jRadioButtonB;
    public javax.swing.JRadioButton jRadioButtonC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaPregunta;
    // End of variables declaration//GEN-END:variables
}
