package Vista.Vistas_Unidad1;

import javax.swing.*;


public class Vista_LeccionSALUDOS extends JPanel {

    public Vista_LeccionSALUDOS() {
        initComponents();

    }
    
  
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedor = new javax.swing.JPanel();
        jPanelPag1 = new javax.swing.JPanel();
        jPanelVideo = new javax.swing.JPanel();
        jButtonSiguientePag = new javax.swing.JButton();
        jButtonPlay = new javax.swing.JButton();
        jButtonPausa = new javax.swing.JButton();
        jSliderProgresoVideo = new javax.swing.JSlider();
        jButtonVoliumen = new javax.swing.JButton();
        jSliderSubirBajarVolumen = new javax.swing.JSlider();
        jLabelTiempoV = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelPag2 = new javax.swing.JPanel();
        jLabelImagen1Saludos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTexto1 = new javax.swing.JTextArea();
        jButtonCOMPLETOSALUDOS = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setPreferredSize(new java.awt.Dimension(1190, 660));

        jPanelContenedor.setMaximumSize(new java.awt.Dimension(1190, 660));
        jPanelContenedor.setMinimumSize(new java.awt.Dimension(1190, 660));
        jPanelContenedor.setPreferredSize(new java.awt.Dimension(1190, 660));
        jPanelContenedor.setLayout(new java.awt.CardLayout());

        jPanelPag1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelVideo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelVideo.setMaximumSize(new java.awt.Dimension(750, 400));
        jPanelVideo.setMinimumSize(new java.awt.Dimension(750, 400));

        javax.swing.GroupLayout jPanelVideoLayout = new javax.swing.GroupLayout(jPanelVideo);
        jPanelVideo.setLayout(jPanelVideoLayout);
        jPanelVideoLayout.setHorizontalGroup(
            jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1038, Short.MAX_VALUE)
        );
        jPanelVideoLayout.setVerticalGroup(
            jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        jPanelPag1.add(jPanelVideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jButtonSiguientePag.setBackground(new java.awt.Color(255, 153, 51));
        jButtonSiguientePag.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSiguientePag.setText("Siguiente");
        jPanelPag1.add(jButtonSiguientePag, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 610, 110, 40));

        jButtonPlay.setBackground(new java.awt.Color(255, 153, 51));
        jButtonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad1/Play.png"))); // NOI18N
        jPanelPag1.add(jButtonPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 50, 40));

        jButtonPausa.setBackground(new java.awt.Color(255, 153, 51));
        jButtonPausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad1/Stop.png"))); // NOI18N
        jPanelPag1.add(jButtonPausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 50, 40));
        jPanelPag1.add(jSliderProgresoVideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 1000, -1));

        jButtonVoliumen.setBackground(new java.awt.Color(255, 153, 51));
        jButtonVoliumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad1/volumen.png"))); // NOI18N
        jPanelPag1.add(jButtonVoliumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 510, 50, 40));

        jSliderSubirBajarVolumen.setOrientation(javax.swing.JSlider.VERTICAL);
        jPanelPag1.add(jSliderSubirBajarVolumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 70, -1, 420));

        jLabelTiempoV.setText("jLabel1");
        jPanelPag1.add(jLabelTiempoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 560, 40, 23));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("SALUDOS EN KICHWA");
        jPanelPag1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 210, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad1/Fondo1U1.jpg"))); // NOI18N
        jPanelPag1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 660));

        jPanelContenedor.add(jPanelPag1, "card2");

        jPanelPag2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImagen1Saludos.setText("jLabel1");
        jPanelPag2.add(jLabelImagen1Saludos, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 32, 459, 549));

        jTextAreaTexto1.setColumns(20);
        jTextAreaTexto1.setRows(5);
        jScrollPane1.setViewportView(jTextAreaTexto1);

        jPanelPag2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 49, 468, 522));

        jButtonCOMPLETOSALUDOS.setBackground(new java.awt.Color(255, 153, 51));
        jButtonCOMPLETOSALUDOS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCOMPLETOSALUDOS.setText("Completar");
        jButtonCOMPLETOSALUDOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCOMPLETOSALUDOSActionPerformed(evt);
            }
        });
        jPanelPag2.add(jButtonCOMPLETOSALUDOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(1044, 597, 130, 47));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad1/Fondo1U1.jpg"))); // NOI18N
        jPanelPag2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 660));

        jPanelContenedor.add(jPanelPag2, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCOMPLETOSALUDOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCOMPLETOSALUDOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCOMPLETOSALUDOSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonCOMPLETOSALUDOS;
    public javax.swing.JButton jButtonPausa;
    public javax.swing.JButton jButtonPlay;
    public javax.swing.JButton jButtonSiguientePag;
    public javax.swing.JButton jButtonVoliumen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabelImagen1Saludos;
    public javax.swing.JLabel jLabelTiempoV;
    public javax.swing.JPanel jPanelContenedor;
    public javax.swing.JPanel jPanelPag1;
    public javax.swing.JPanel jPanelPag2;
    public javax.swing.JPanel jPanelVideo;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSlider jSliderProgresoVideo;
    public javax.swing.JSlider jSliderSubirBajarVolumen;
    public javax.swing.JTextArea jTextAreaTexto1;
    // End of variables declaration//GEN-END:variables
}
