/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Vistas_Unidad1;

import java.awt.CardLayout;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DragGestureEvent;
import java.awt.dnd.DragGestureListener;
import java.awt.dnd.DragSource;
import java.awt.dnd.DragSourceDragEvent;
import java.awt.dnd.DragSourceDropEvent;
import java.awt.dnd.DragSourceEvent;
import java.awt.dnd.DragSourceListener;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetDragEvent;
import java.awt.dnd.DropTargetDropEvent;
import java.awt.dnd.DropTargetEvent;
import java.awt.dnd.DropTargetListener;
import javax.swing.JLabel;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_Actividad2U1 extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad2U1
     */
    public Vista_Actividad2U1() {
        initComponents();
        configurarCardLayout();
        configurarDragAndDrop();
    }

    private void configurarCardLayout() {
        CardLayout cl = new CardLayout();
        jPanelContenedor.setLayout(cl);

        jPanelContenedor.add(jPanelEmparejar, "Emparejar");
        jPanelContenedor.add(jPanelDragDrop, "DragDrop");
    }

    private void configurarDragAndDrop() {
        // Listener para iniciar el drag
        DragSourceListener dragSourceListener = new DragSourceListener() {
            public void dragEnter(DragSourceDragEvent dsde) {
            }

            public void dragOver(DragSourceDragEvent dsde) {
            }

            public void dropActionChanged(DragSourceDragEvent dsde) {
            }

            public void dragExit(DragSourceEvent dse) {
            }

            public void dragDropEnd(DragSourceDropEvent dsde) {
            }
        };

        DragGestureListener dragGestureListener = new DragGestureListener() {
            public void dragGestureRecognized(DragGestureEvent dge) {
                JLabel label = (JLabel) dge.getComponent();
                StringSelection text = new StringSelection(label.getText());
                dge.startDrag(DragSource.DefaultCopyDrop, text, dragSourceListener);
            }
        };

        DragSource ds = new DragSource();
        ds.createDefaultDragGestureRecognizer(jLabelDragDropOpcionA, DnDConstants.ACTION_COPY, dragGestureListener);
        ds.createDefaultDragGestureRecognizer(jLabelDragDropOpcionB, DnDConstants.ACTION_COPY, dragGestureListener);
        ds.createDefaultDragGestureRecognizer(jLabelDragDropOpcionC, DnDConstants.ACTION_COPY, dragGestureListener);

        // Receptor (DropTarget) para el destino
        new DropTarget(jLabelDestino, new DropTargetListener() {
            public void dragEnter(DropTargetDragEvent dtde) {
            }

            public void dragOver(DropTargetDragEvent dtde) {
            }

            public void dropActionChanged(DropTargetDragEvent dtde) {
            }

            public void dragExit(DropTargetEvent dte) {
            }

            public void drop(DropTargetDropEvent dtde) {
                try {
                    dtde.acceptDrop(DnDConstants.ACTION_COPY);
                    String data = (String) dtde.getTransferable().getTransferData(DataFlavor.stringFlavor);
                    jLabelDestino.setText(data);
                    dtde.dropComplete(true);
                } catch (Exception ex) {
                    dtde.dropComplete(false);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedor = new javax.swing.JPanel();
        jPanelDragDrop = new javax.swing.JPanel();
        jLabelDestino = new javax.swing.JLabel();
        jLabelDragDropOpcionA = new javax.swing.JLabel();
        jLabelDragDropOpcionB = new javax.swing.JLabel();
        jLabelDragDropOpcionC = new javax.swing.JLabel();
        jButtonValidarDragDrop = new javax.swing.JButton();
        jButtonCOMPLETOACTV2 = new javax.swing.JButton();
        jLabelMensajeRespuesta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelPreguntaDragDrop = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelEmparejar = new javax.swing.JPanel();
        jComboBoxEmparejarOpcionA = new javax.swing.JComboBox<>();
        jComboBoxEmparejarOpcionB = new javax.swing.JComboBox<>();
        jComboBoxEmparejarOpcionC = new javax.swing.JComboBox<>();
        jLabelEmaprejar1 = new javax.swing.JLabel();
        jLabelEmaprejar2 = new javax.swing.JLabel();
        jLabelEmaprejar3 = new javax.swing.JLabel();
        jButtonValidarEmparejar = new javax.swing.JButton();
        LabelTitulo = new javax.swing.JLabel();
        jLabelPreguntaEmparejar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setPreferredSize(new java.awt.Dimension(1190, 660));

        jPanelContenedor.setPreferredSize(new java.awt.Dimension(1190, 626));
        jPanelContenedor.setLayout(new java.awt.CardLayout());

        jPanelDragDrop.setMaximumSize(new java.awt.Dimension(691, 587));
        jPanelDragDrop.setMinimumSize(new java.awt.Dimension(691, 587));
        jPanelDragDrop.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanelDragDrop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDestino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDestino.setText("ARRASTRA TU PALABAR AQUÍ");
        jLabelDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelDragDrop.add(jLabelDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 303, 75));

        jLabelDragDropOpcionA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDragDropOpcionA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelDragDrop.add(jLabelDragDropOpcionA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 200, 50));

        jLabelDragDropOpcionB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDragDropOpcionB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelDragDrop.add(jLabelDragDropOpcionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 200, 50));

        jLabelDragDropOpcionC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDragDropOpcionC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelDragDrop.add(jLabelDragDropOpcionC, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, 200, 50));

        jButtonValidarDragDrop.setBackground(new java.awt.Color(255, 153, 51));
        jButtonValidarDragDrop.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonValidarDragDrop.setText("Validar");
        jPanelDragDrop.add(jButtonValidarDragDrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 111, 45));

        jButtonCOMPLETOACTV2.setBackground(new java.awt.Color(255, 153, 51));
        jButtonCOMPLETOACTV2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCOMPLETOACTV2.setText("TERMINADO");
        jButtonCOMPLETOACTV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCOMPLETOACTV2ActionPerformed(evt);
            }
        });
        jPanelDragDrop.add(jButtonCOMPLETOACTV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 590, 150, 40));

        jLabelMensajeRespuesta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMensajeRespuesta.setText("Respuesta");
        jPanelDragDrop.add(jLabelMensajeRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 170, 28));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("DRAG-DROP");
        jLabel3.setToolTipText("");
        jPanelDragDrop.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 230, 60));

        jLabelPreguntaDragDrop.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPreguntaDragDrop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelDragDrop.add(jLabelPreguntaDragDrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 650, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad1/Fondo1U1.jpg"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanelDragDrop.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 660));

        jPanelContenedor.add(jPanelDragDrop, "card5");

        jPanelEmparejar.setMaximumSize(new java.awt.Dimension(691, 587));
        jPanelEmparejar.setMinimumSize(new java.awt.Dimension(691, 587));
        jPanelEmparejar.setPreferredSize(new java.awt.Dimension(1190, 626));
        jPanelEmparejar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxEmparejarOpcionA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEmparejarOpcionA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanelEmparejar.add(jComboBoxEmparejarOpcionA, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 170, 60));

        jComboBoxEmparejarOpcionB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEmparejarOpcionB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanelEmparejar.add(jComboBoxEmparejarOpcionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 170, 60));

        jComboBoxEmparejarOpcionC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEmparejarOpcionC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jComboBoxEmparejarOpcionC.setPreferredSize(new java.awt.Dimension(170, 50));
        jPanelEmparejar.add(jComboBoxEmparejarOpcionC, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 170, 60));

        jLabelEmaprejar1.setText("jLabel2");
        jLabelEmaprejar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanelEmparejar.add(jLabelEmaprejar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 170, 60));

        jLabelEmaprejar2.setText("jLabel3");
        jLabelEmaprejar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanelEmparejar.add(jLabelEmaprejar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 170, 60));

        jLabelEmaprejar3.setText("jLabel4");
        jLabelEmaprejar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanelEmparejar.add(jLabelEmaprejar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 170, 60));

        jButtonValidarEmparejar.setBackground(new java.awt.Color(255, 153, 51));
        jButtonValidarEmparejar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonValidarEmparejar.setText("Validar Emparejamiento");
        jButtonValidarEmparejar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelEmparejar.add(jButtonValidarEmparejar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 567, 250, 40));

        LabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LabelTitulo.setText("EMPAREJAR");
        jPanelEmparejar.add(LabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 220, 50));

        jLabelPreguntaEmparejar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPreguntaEmparejar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelEmparejar.add(jLabelPreguntaEmparejar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 750, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad1/Fondo1U1.jpg"))); // NOI18N
        jPanelEmparejar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1190, 700));

        jPanelContenedor.add(jPanelEmparejar, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCOMPLETOACTV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCOMPLETOACTV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCOMPLETOACTV2ActionPerformed

//Variables  Vista_Actividad2U1
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel LabelTitulo;
    public javax.swing.JButton jButtonCOMPLETOACTV2;
    public javax.swing.JButton jButtonValidarDragDrop;
    public javax.swing.JButton jButtonValidarEmparejar;
    public javax.swing.JComboBox<String> jComboBoxEmparejarOpcionA;
    public javax.swing.JComboBox<String> jComboBoxEmparejarOpcionB;
    public javax.swing.JComboBox<String> jComboBoxEmparejarOpcionC;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabelDestino;
    public javax.swing.JLabel jLabelDragDropOpcionA;
    public javax.swing.JLabel jLabelDragDropOpcionB;
    public javax.swing.JLabel jLabelDragDropOpcionC;
    public javax.swing.JLabel jLabelEmaprejar1;
    public javax.swing.JLabel jLabelEmaprejar2;
    public javax.swing.JLabel jLabelEmaprejar3;
    public javax.swing.JLabel jLabelMensajeRespuesta;
    public javax.swing.JLabel jLabelPreguntaDragDrop;
    public javax.swing.JLabel jLabelPreguntaEmparejar;
    public javax.swing.JPanel jPanelContenedor;
    public javax.swing.JPanel jPanelDragDrop;
    public javax.swing.JPanel jPanelEmparejar;
    // End of variables declaration//GEN-END:variables
}
