/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Dimension;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author Bryan
 */
public class Graficos extends javax.swing.JPanel {

    /**
     * Creates new form Graficos
     */
    public Graficos() {
        initComponents();
        PanelGraficos.setPreferredSize(new Dimension(1190,600));
    }

    public JPanel getPanelGraficos() {
        return PanelGraficos;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JRadioButton getRdAreas() {
        return rdAreas;
    }

    public JRadioButton getRdBarras() {
        return rdBarras;
    }

    public JRadioButton getRdLineas() {
        return rdLineas;
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelGraficos = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        rdBarras = new javax.swing.JRadioButton();
        rdLineas = new javax.swing.JRadioButton();
        rdAreas = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        PanelGraficos.setMaximumSize(new java.awt.Dimension(1190, 600));
        PanelGraficos.setMinimumSize(new java.awt.Dimension(1190, 600));

        javax.swing.GroupLayout PanelGraficosLayout = new javax.swing.GroupLayout(PanelGraficos);
        PanelGraficos.setLayout(PanelGraficosLayout);
        PanelGraficosLayout.setHorizontalGroup(
            PanelGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        PanelGraficosLayout.setVerticalGroup(
            PanelGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Filtrar por:");

        buttonGroup1.add(rdBarras);
        rdBarras.setText("Barras");

        buttonGroup1.add(rdLineas);
        rdLineas.setText("Pastel");

        buttonGroup1.add(rdAreas);
        rdAreas.setText("Areas");

        jLabel2.setText("Tipo de grafico:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdBarras)
                .addGap(33, 33, 33)
                .addComponent(rdLineas)
                .addGap(29, 29, 29)
                .addComponent(rdAreas)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(rdBarras)
                    .addComponent(rdLineas)
                    .addComponent(rdAreas)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(PanelGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanelGraficos;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JRadioButton rdAreas;
    public javax.swing.JRadioButton rdBarras;
    public javax.swing.JRadioButton rdLineas;
    // End of variables declaration//GEN-END:variables
}
