/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_InicioOperacionesUnidad2 extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad1U1
     */
    public Vista_InicioOperacionesUnidad2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2debeaparecer1 = new javax.swing.JLabel();
        jLabel3debeaparecersegundo = new javax.swing.JLabel();
        jLabel1debeaparecercuarto = new javax.swing.JLabel();
        jLabel1debeaparecertercero2 = new javax.swing.JLabel();
        jLabel1debeaparecercdecimo = new javax.swing.JLabel();
        jLabel1debeaparecertercero = new javax.swing.JLabel();
        jLabel1debeaparecercquinto1 = new javax.swing.JLabel();
        jLabel1debeaparecercsexto1 = new javax.swing.JLabel();
        jLabel1debeaparecercseptimo1 = new javax.swing.JLabel();
        jLabel1debeaparecercsoctavo1 = new javax.swing.JLabel();
        jLabel1debeaparecercsonoveno = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2debeaparecer1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2debeaparecer1.setText("ALLI PUNCHA");
        add(jLabel2debeaparecer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel3debeaparecersegundo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3debeaparecersegundo.setText("ISHKINTI RURASHUN ISHKINTI RURASHUN ");
        add(jLabel3debeaparecersegundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel1debeaparecercuarto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecercuarto.setText("Ahora vamos a escribir todo en una hoja");
        add(jLabel1debeaparecercuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel1debeaparecertercero2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecertercero2.setText("¿Qué vamos a hacer juntos?");
        add(jLabel1debeaparecertercero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel1debeaparecercdecimo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecercdecimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad2/4.png"))); // NOI18N
        add(jLabel1debeaparecercdecimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 510, -1, 50));

        jLabel1debeaparecertercero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1debeaparecertercero.setText("Kunan shuk pankapi killkashpa tukuy");
        add(jLabel1debeaparecertercero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel1debeaparecercquinto1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1debeaparecercquinto1.setText("SHUK YAPACHUK SHUK ANCHUCHIK YACHASHUN ");
        add(jLabel1debeaparecercquinto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        jLabel1debeaparecercsexto1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecercsexto1.setText("VAMOS HACER SUMAS Y RESTAS ");
        add(jLabel1debeaparecercsexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, -1, -1));

        jLabel1debeaparecercseptimo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecercseptimo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad2/1.png"))); // NOI18N
        add(jLabel1debeaparecercseptimo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, -1, 50));

        jLabel1debeaparecercsoctavo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecercsoctavo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad2/2.png"))); // NOI18N
        add(jLabel1debeaparecercsoctavo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, -1, 50));

        jLabel1debeaparecercsonoveno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecercsonoveno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad2/3.png"))); // NOI18N
        add(jLabel1debeaparecercsonoveno, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 250, 50));

        jButton1.setText("CONTINUAR");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 620, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1debeaparecercdecimo;
    private javax.swing.JLabel jLabel1debeaparecercquinto1;
    private javax.swing.JLabel jLabel1debeaparecercseptimo1;
    private javax.swing.JLabel jLabel1debeaparecercsexto1;
    private javax.swing.JLabel jLabel1debeaparecercsoctavo1;
    private javax.swing.JLabel jLabel1debeaparecercsonoveno;
    private javax.swing.JLabel jLabel1debeaparecercuarto;
    private javax.swing.JLabel jLabel1debeaparecertercero;
    private javax.swing.JLabel jLabel1debeaparecertercero2;
    private javax.swing.JLabel jLabel2debeaparecer1;
    private javax.swing.JLabel jLabel3debeaparecersegundo;
    // End of variables declaration//GEN-END:variables
}
