/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.text.*;
import javax.swing.*;
/**
 *
 * @author Jhony Espinoza
 */
public class Vista_NumerosActividadUnidad2 extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad1U1
     */
    public Vista_NumerosActividadUnidad2() {
        initComponents();
         forzarMayusculas();
    }
    private void forzarMayusculas() {
        DocumentFilter upperCaseFilter = new DocumentFilter() {
            @Override
            public void insertString(FilterBypass fb, int offset, String text, AttributeSet attr)
                    throws BadLocationException {
                fb.insertString(offset, text.toUpperCase(), attr);
            }

            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
                    throws BadLocationException {
                fb.replace(offset, length, text.toUpperCase(), attrs);
            }
        };

        PlainDocument[] docs = new PlainDocument[]{
            (PlainDocument) jTextField1Numero1.getDocument(),
            (PlainDocument) jTextField1Numero2.getDocument(),
            (PlainDocument) jTextField1Numero3.getDocument(),
            (PlainDocument) jTextField1Numero4.getDocument(),
            (PlainDocument) jTextField1Numero5.getDocument(),
            (PlainDocument) jTextField1Numero6.getDocument(),
            (PlainDocument) jTextField1Numero7.getDocument(),
            (PlainDocument) jTextField1Numero8.getDocument(),
            (PlainDocument) jTextField1Numero9.getDocument(),
            (PlainDocument) jTextField1Numero10.getDocument()
        };

        for (PlainDocument doc : docs) {
            doc.setDocumentFilter(upperCaseFilter);
        }
    }

    public JButton getjButton1ComprobarAudios() {
        return jButton1ComprobarAudios;
    }

    public JButton getjButton1Continuar() {
        return jButton1Continuar;
    }

    public JButton[] getBotonesAudio() {
        return new JButton[]{
            jButton1audio1, jButton1audio2, jButton1audio3, jButton1audio4, jButton1audio5,
            jButton1audio6, jButton1audio7, jButton1audio8, jButton1audio9, jButton1audio10
        };
    }

public String[] getRespuestasIngresadas() {
    return new String[]{
        jTextField1Numero1.getText(),
        jTextField1Numero2.getText(),
        jTextField1Numero3.getText(),
        jTextField1Numero4.getText(),
        jTextField1Numero5.getText(),
        jTextField1Numero6.getText(),
        jTextField1Numero7.getText(),
        jTextField1Numero8.getText(),
        jTextField1Numero9.getText(),
        jTextField1Numero10.getText()
    };
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2EscuchayEscribe = new javax.swing.JLabel();
        jLabel2debeaparecer2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1audio3 = new javax.swing.JButton();
        jButton1audio1 = new javax.swing.JButton();
        jTextField1Numero1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1audio2 = new javax.swing.JButton();
        jTextField1Numero2 = new javax.swing.JTextField();
        jTextField1Numero3 = new javax.swing.JTextField();
        jTextField1Numero4 = new javax.swing.JTextField();
        jButton1audio4 = new javax.swing.JButton();
        jTextField1Numero5 = new javax.swing.JTextField();
        jButton1audio5 = new javax.swing.JButton();
        jTextField1Numero6 = new javax.swing.JTextField();
        jButton1audio6 = new javax.swing.JButton();
        jButton1audio7 = new javax.swing.JButton();
        jTextField1Numero7 = new javax.swing.JTextField();
        jButton1audio8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField1Numero8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField1Numero9 = new javax.swing.JTextField();
        jButton1audio9 = new javax.swing.JButton();
        jTextField1Numero10 = new javax.swing.JTextField();
        jButton1audio10 = new javax.swing.JButton();
        jButton1ComprobarAudios = new javax.swing.JButton();
        jButton1Continuar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2EscuchayEscribe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2EscuchayEscribe.setText("Escucha y Escribe ");
        add(jLabel2EscuchayEscribe, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jLabel2debeaparecer2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2debeaparecer2.setText("KALLARINKAPAK ");
        add(jLabel2debeaparecer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jLabel1.setText("---------------------------");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        jLabel2.setText("---------------------------");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        jLabel3.setText("---------------------------");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        jLabel4.setText("---------------------------");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, -1, -1));

        jLabel5.setText("---------------------------");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jLabel6.setText("---------------------------");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, -1, -1));

        jLabel7.setText("---------------------------");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        jButton1audio3.setText("📢");
        add(jButton1audio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        jButton1audio1.setText("📢");
        add(jButton1audio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));
        add(jTextField1Numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 130, -1));

        jLabel8.setText("---------------------------");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, -1, -1));

        jButton1audio2.setText("📢");
        add(jButton1audio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));
        add(jTextField1Numero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 130, -1));
        add(jTextField1Numero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 130, -1));
        add(jTextField1Numero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 130, -1));

        jButton1audio4.setText("📢");
        add(jButton1audio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));
        add(jTextField1Numero5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 130, -1));

        jButton1audio5.setText("📢");
        add(jButton1audio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));
        add(jTextField1Numero6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 130, -1));

        jButton1audio6.setText("📢");
        add(jButton1audio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));

        jButton1audio7.setText("📢");
        add(jButton1audio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));
        add(jTextField1Numero7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 130, -1));

        jButton1audio8.setText("📢");
        add(jButton1audio8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));

        jLabel10.setText("---------------------------");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, -1, -1));
        add(jTextField1Numero8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 130, -1));

        jLabel9.setText("---------------------------");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));
        add(jTextField1Numero9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 130, -1));

        jButton1audio9.setText("📢");
        add(jButton1audio9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));
        add(jTextField1Numero10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 130, -1));

        jButton1audio10.setText("📢");
        jButton1audio10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1audio10ActionPerformed(evt);
            }
        });
        add(jButton1audio10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        jButton1ComprobarAudios.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jButton1ComprobarAudios.setText("Comprobar");
        add(jButton1ComprobarAudios, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, -1));

        jButton1Continuar.setBackground(new java.awt.Color(255, 122, 0));
        jButton1Continuar.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jButton1Continuar.setText("CONTINUAR");
        add(jButton1Continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 610, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad2/Fondo2.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-22, -84, 1230, 750));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1audio10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1audio10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1audio10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ComprobarAudios;
    private javax.swing.JButton jButton1Continuar;
    private javax.swing.JButton jButton1audio1;
    private javax.swing.JButton jButton1audio10;
    private javax.swing.JButton jButton1audio2;
    private javax.swing.JButton jButton1audio3;
    private javax.swing.JButton jButton1audio4;
    private javax.swing.JButton jButton1audio5;
    private javax.swing.JButton jButton1audio6;
    private javax.swing.JButton jButton1audio7;
    private javax.swing.JButton jButton1audio8;
    private javax.swing.JButton jButton1audio9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2EscuchayEscribe;
    private javax.swing.JLabel jLabel2debeaparecer2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1Numero1;
    private javax.swing.JTextField jTextField1Numero10;
    private javax.swing.JTextField jTextField1Numero2;
    private javax.swing.JTextField jTextField1Numero3;
    private javax.swing.JTextField jTextField1Numero4;
    private javax.swing.JTextField jTextField1Numero5;
    private javax.swing.JTextField jTextField1Numero6;
    private javax.swing.JTextField jTextField1Numero7;
    private javax.swing.JTextField jTextField1Numero8;
    private javax.swing.JTextField jTextField1Numero9;
    // End of variables declaration//GEN-END:variables
}
