/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_Actividad1U1 extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad1U1
     */
    public Vista_Actividad1U1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupOpciones = new javax.swing.ButtonGroup();
        buttonGroupOpcionesPag2 = new javax.swing.ButtonGroup();
        jPanelContenedor = new javax.swing.JPanel();
        jPanelAPag2 = new javax.swing.JPanel();
        jPanelAPag1 = new javax.swing.JPanel();
        jPanelPregunta1 = new javax.swing.JPanel();
        jRadioButtonOpcion1 = new javax.swing.JRadioButton();
        jRadioButtonOpcion2 = new javax.swing.JRadioButton();
        jRadioButtonOpcion3 = new javax.swing.JRadioButton();
        jButtonResponder = new javax.swing.JButton();
        jLabelMensajeRespuesta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPregunta = new javax.swing.JTextArea();
        jPanelPregunta2 = new javax.swing.JPanel();
        jRadioButtonOpcion4 = new javax.swing.JRadioButton();
        jRadioButtonOpcion5 = new javax.swing.JRadioButton();
        jRadioButtonOpcion6 = new javax.swing.JRadioButton();
        jButtonResponder1 = new javax.swing.JButton();
        jLabelMensajeRespuesta1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaPregunta1 = new javax.swing.JTextArea();
        jPanelPregunta3 = new javax.swing.JPanel();
        jRadioButtonOpcion7 = new javax.swing.JRadioButton();
        jRadioButtonOpcion8 = new javax.swing.JRadioButton();
        jRadioButtonOpcion9 = new javax.swing.JRadioButton();
        jButtonResponder2 = new javax.swing.JButton();
        jLabelMensajeRespuesta2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaPregunta2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButtonCOMPLETOACTV1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setPreferredSize(new java.awt.Dimension(1190, 660));

        jPanelContenedor.setMaximumSize(new java.awt.Dimension(1190, 660));
        jPanelContenedor.setMinimumSize(new java.awt.Dimension(1190, 660));
        jPanelContenedor.setName(""); // NOI18N
        jPanelContenedor.setPreferredSize(new java.awt.Dimension(1190, 660));
        jPanelContenedor.setLayout(new java.awt.CardLayout());

        jPanelAPag2.setMaximumSize(new java.awt.Dimension(1190, 660));
        jPanelAPag2.setMinimumSize(new java.awt.Dimension(1190, 660));

        javax.swing.GroupLayout jPanelAPag2Layout = new javax.swing.GroupLayout(jPanelAPag2);
        jPanelAPag2.setLayout(jPanelAPag2Layout);
        jPanelAPag2Layout.setHorizontalGroup(
            jPanelAPag2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        jPanelAPag2Layout.setVerticalGroup(
            jPanelAPag2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanelContenedor.add(jPanelAPag2, "card2");

        jPanelAPag1.setAutoscrolls(true);
        jPanelAPag1.setFocusCycleRoot(true);
        jPanelAPag1.setLayout(new javax.swing.BoxLayout(jPanelAPag1, javax.swing.BoxLayout.Y_AXIS));

        jPanelPregunta1.setMaximumSize(new java.awt.Dimension(500, 290));
        jPanelPregunta1.setMinimumSize(new java.awt.Dimension(500, 290));
        jPanelPregunta1.setName(""); // NOI18N
        jPanelPregunta1.setPreferredSize(new java.awt.Dimension(500, 290));

        buttonGroupOpciones.add(jRadioButtonOpcion1);
        jRadioButtonOpcion1.setText("jRadioButton1");
        jRadioButtonOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOpcion1ActionPerformed(evt);
            }
        });

        buttonGroupOpciones.add(jRadioButtonOpcion2);
        jRadioButtonOpcion2.setText("jRadioButton2");

        buttonGroupOpciones.add(jRadioButtonOpcion3);
        jRadioButtonOpcion3.setText("jRadioButton3");

        jButtonResponder.setText("jButton1");

        jLabelMensajeRespuesta.setText("jLabel2");

        jTextAreaPregunta.setColumns(20);
        jTextAreaPregunta.setLineWrap(true);
        jTextAreaPregunta.setRows(5);
        jTextAreaPregunta.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaPregunta);

        javax.swing.GroupLayout jPanelPregunta1Layout = new javax.swing.GroupLayout(jPanelPregunta1);
        jPanelPregunta1.setLayout(jPanelPregunta1Layout);
        jPanelPregunta1Layout.setHorizontalGroup(
            jPanelPregunta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPregunta1Layout.createSequentialGroup()
                .addGroup(jPanelPregunta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPregunta1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanelPregunta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMensajeRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPregunta1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(jPanelPregunta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jRadioButtonOpcion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonOpcion1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonOpcion3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPregunta1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jButtonResponder, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanelPregunta1Layout.setVerticalGroup(
            jPanelPregunta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPregunta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMensajeRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonOpcion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonOpcion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonOpcion2)
                .addGap(32, 32, 32)
                .addComponent(jButtonResponder, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAPag1.add(jPanelPregunta1);

        jPanelPregunta2.setMaximumSize(new java.awt.Dimension(500, 290));
        jPanelPregunta2.setMinimumSize(new java.awt.Dimension(500, 290));
        jPanelPregunta2.setName(""); // NOI18N

        buttonGroupOpciones.add(jRadioButtonOpcion4);
        jRadioButtonOpcion4.setText("jRadioButton1");
        jRadioButtonOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOpcion4ActionPerformed(evt);
            }
        });

        buttonGroupOpciones.add(jRadioButtonOpcion5);
        jRadioButtonOpcion5.setText("jRadioButton2");

        buttonGroupOpciones.add(jRadioButtonOpcion6);
        jRadioButtonOpcion6.setText("jRadioButton3");

        jButtonResponder1.setText("jButton1");

        jLabelMensajeRespuesta1.setText("jLabel2");

        jTextAreaPregunta1.setColumns(20);
        jTextAreaPregunta1.setLineWrap(true);
        jTextAreaPregunta1.setRows(5);
        jTextAreaPregunta1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextAreaPregunta1);

        javax.swing.GroupLayout jPanelPregunta2Layout = new javax.swing.GroupLayout(jPanelPregunta2);
        jPanelPregunta2.setLayout(jPanelPregunta2Layout);
        jPanelPregunta2Layout.setHorizontalGroup(
            jPanelPregunta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPregunta2Layout.createSequentialGroup()
                .addGroup(jPanelPregunta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPregunta2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanelPregunta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMensajeRespuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPregunta2Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(jPanelPregunta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jRadioButtonOpcion5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonOpcion4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonOpcion6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPregunta2Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jButtonResponder1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanelPregunta2Layout.setVerticalGroup(
            jPanelPregunta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPregunta2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMensajeRespuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonOpcion4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonOpcion6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonOpcion5)
                .addGap(32, 32, 32)
                .addComponent(jButtonResponder1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAPag1.add(jPanelPregunta2);

        jPanelPregunta3.setMaximumSize(new java.awt.Dimension(500, 290));
        jPanelPregunta3.setMinimumSize(new java.awt.Dimension(500, 290));
        jPanelPregunta3.setName(""); // NOI18N

        buttonGroupOpciones.add(jRadioButtonOpcion7);
        jRadioButtonOpcion7.setText("jRadioButton1");
        jRadioButtonOpcion7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOpcion7ActionPerformed(evt);
            }
        });

        buttonGroupOpciones.add(jRadioButtonOpcion8);
        jRadioButtonOpcion8.setText("jRadioButton2");

        buttonGroupOpciones.add(jRadioButtonOpcion9);
        jRadioButtonOpcion9.setText("jRadioButton3");

        jButtonResponder2.setText("jButton1");

        jLabelMensajeRespuesta2.setText("jLabel2");

        jTextAreaPregunta2.setColumns(20);
        jTextAreaPregunta2.setLineWrap(true);
        jTextAreaPregunta2.setRows(5);
        jTextAreaPregunta2.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextAreaPregunta2);

        javax.swing.GroupLayout jPanelPregunta3Layout = new javax.swing.GroupLayout(jPanelPregunta3);
        jPanelPregunta3.setLayout(jPanelPregunta3Layout);
        jPanelPregunta3Layout.setHorizontalGroup(
            jPanelPregunta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPregunta3Layout.createSequentialGroup()
                .addGroup(jPanelPregunta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPregunta3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanelPregunta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMensajeRespuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPregunta3Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(jPanelPregunta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jRadioButtonOpcion8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonOpcion7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonOpcion9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPregunta3Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jButtonResponder2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanelPregunta3Layout.setVerticalGroup(
            jPanelPregunta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPregunta3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMensajeRespuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonOpcion7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonOpcion9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonOpcion8)
                .addGap(32, 32, 32)
                .addComponent(jButtonResponder2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAPag1.add(jPanelPregunta3);

        jPanel1.setMaximumSize(new java.awt.Dimension(1588, 150));
        jPanel1.setMinimumSize(new java.awt.Dimension(1588, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(1588, 150));

        jButtonCOMPLETOACTV1.setText("Terminado");
        jButtonCOMPLETOACTV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCOMPLETOACTV1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1392, Short.MAX_VALUE)
                .addComponent(jButtonCOMPLETOACTV1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jButtonCOMPLETOACTV1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanelAPag1.add(jPanel1);

        jPanelContenedor.add(jPanelAPag1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCOMPLETOACTV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCOMPLETOACTV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCOMPLETOACTV1ActionPerformed

    private void jRadioButtonOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOpcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonOpcion1ActionPerformed

    private void jRadioButtonOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOpcion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonOpcion4ActionPerformed

    private void jRadioButtonOpcion7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOpcion7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonOpcion7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroupOpciones;
    public javax.swing.ButtonGroup buttonGroupOpcionesPag2;
    public javax.swing.JButton jButtonCOMPLETOACTV1;
    public javax.swing.JButton jButtonResponder;
    public javax.swing.JButton jButtonResponder1;
    public javax.swing.JButton jButtonResponder2;
    public javax.swing.JLabel jLabelMensajeRespuesta;
    public javax.swing.JLabel jLabelMensajeRespuesta1;
    public javax.swing.JLabel jLabelMensajeRespuesta2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanelAPag1;
    public javax.swing.JPanel jPanelAPag2;
    public javax.swing.JPanel jPanelContenedor;
    public javax.swing.JPanel jPanelPregunta1;
    public javax.swing.JPanel jPanelPregunta2;
    public javax.swing.JPanel jPanelPregunta3;
    public javax.swing.JRadioButton jRadioButtonOpcion1;
    public javax.swing.JRadioButton jRadioButtonOpcion2;
    public javax.swing.JRadioButton jRadioButtonOpcion3;
    public javax.swing.JRadioButton jRadioButtonOpcion4;
    public javax.swing.JRadioButton jRadioButtonOpcion5;
    public javax.swing.JRadioButton jRadioButtonOpcion6;
    public javax.swing.JRadioButton jRadioButtonOpcion7;
    public javax.swing.JRadioButton jRadioButtonOpcion8;
    public javax.swing.JRadioButton jRadioButtonOpcion9;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextArea jTextAreaPregunta;
    public javax.swing.JTextArea jTextAreaPregunta1;
    public javax.swing.JTextArea jTextAreaPregunta2;
    // End of variables declaration//GEN-END:variables
}
