/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_ActividadOperacionesUnidad2 extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad1U1
     */
    public Vista_ActividadOperacionesUnidad2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2debeaparecer2 = new javax.swing.JLabel();
        jButton1ComprobarAudios = new javax.swing.JButton();
        jLabel2debeaparecer3 = new javax.swing.JLabel();
        jTextField1Numero2 = new javax.swing.JTextField();
        jTextFieldSumarestamultiplicaciondivision = new javax.swing.JTextField();
        jTextField1PrimerNumero1 = new javax.swing.JTextField();
        jLabel1resultado = new javax.swing.JLabel();
        jTextField1Resultado1 = new javax.swing.JTextField();
        jTextField1Resultado2 = new javax.swing.JTextField();
        jTextField1Numero3 = new javax.swing.JTextField();
        jTextFieldSumarestamultiplicaciondivision1 = new javax.swing.JTextField();
        jTextField1Numero4 = new javax.swing.JTextField();
        jLabel1resultado1 = new javax.swing.JLabel();
        jTextField1Numero5 = new javax.swing.JTextField();
        jTextFieldSumarestamultiplicaciondivision2 = new javax.swing.JTextField();
        jTextField1Numero6 = new javax.swing.JTextField();
        jLabel1resultado2 = new javax.swing.JLabel();
        jTextField1Resultado3 = new javax.swing.JTextField();
        jTextField1Numero7 = new javax.swing.JTextField();
        jTextField1Numero8 = new javax.swing.JTextField();
        jLabel1resultado3 = new javax.swing.JLabel();
        jTextFieldSumarestamultiplicaciondivision3 = new javax.swing.JTextField();
        jTextField1Resultado4 = new javax.swing.JTextField();
        jTextField1Numero9 = new javax.swing.JTextField();
        jTextField1Numero10 = new javax.swing.JTextField();
        jLabel1resultado4 = new javax.swing.JLabel();
        jTextField1Resultado5 = new javax.swing.JTextField();
        jTextFieldSumarestamultiplicaciondivision4 = new javax.swing.JTextField();
        jTextField1Numero11 = new javax.swing.JTextField();
        jTextField1Resultado6 = new javax.swing.JTextField();
        jTextFieldSumarestamultiplicaciondivision5 = new javax.swing.JTextField();
        jLabel1resultado5 = new javax.swing.JLabel();
        jTextField1Numero12 = new javax.swing.JTextField();
        jTextField1Resultado7 = new javax.swing.JTextField();
        jTextField1Numero13 = new javax.swing.JTextField();
        jTextFieldSumarestamultiplicaciondivision6 = new javax.swing.JTextField();
        jTextField1Numero14 = new javax.swing.JTextField();
        jLabel1resultado6 = new javax.swing.JLabel();
        jTextField1Resultado8 = new javax.swing.JTextField();
        jTextField1Numero15 = new javax.swing.JTextField();
        jTextField1Numero16 = new javax.swing.JTextField();
        jLabel1resultado7 = new javax.swing.JLabel();
        jTextFieldSumarestamultiplicaciondivision7 = new javax.swing.JTextField();
        jTextField1Numero17 = new javax.swing.JTextField();
        jLabel1resultado8 = new javax.swing.JLabel();
        jTextField1Resultado9 = new javax.swing.JTextField();
        jTextFieldSumarestamultiplicaciondivision8 = new javax.swing.JTextField();
        jTextField1Numero18 = new javax.swing.JTextField();
        jLabel1resultado9 = new javax.swing.JLabel();
        jTextField1Numero19 = new javax.swing.JTextField();
        jTextFieldSumarestamultiplicaciondivision9 = new javax.swing.JTextField();
        jTextField1Resultado10 = new javax.swing.JTextField();
        jTextField1Numero20 = new javax.swing.JTextField();
        jTextField1Resultado11 = new javax.swing.JTextField();
        jTextField1Numero21 = new javax.swing.JTextField();
        jTextField1Numero22 = new javax.swing.JTextField();
        jTextFieldSumarestamultiplicaciondivision10 = new javax.swing.JTextField();
        jLabel1resultado10 = new javax.swing.JLabel();
        jTextField1Numero23 = new javax.swing.JTextField();
        jTextField1Resultado12 = new javax.swing.JTextField();
        jLabel1resultado11 = new javax.swing.JLabel();
        jTextField1Numero24 = new javax.swing.JTextField();
        jTextFieldSumarestamultiplicaciondivision11 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2debeaparecer2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2debeaparecer2.setText("Selecciona la operación correcta");
        add(jLabel2debeaparecer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jButton1ComprobarAudios.setText("Comprobar");
        add(jButton1ComprobarAudios, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, -1, -1));

        jLabel2debeaparecer3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2debeaparecer3.setText("RURAY ");
        add(jLabel2debeaparecer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));
        add(jTextField1Numero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 60, -1));
        add(jTextFieldSumarestamultiplicaciondivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 30, -1));
        add(jTextField1PrimerNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 60, -1));

        jLabel1resultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1resultado.setText("=");
        add(jLabel1resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, 20));
        add(jTextField1Resultado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 250, -1));
        add(jTextField1Resultado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 250, -1));
        add(jTextField1Numero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 60, -1));
        add(jTextFieldSumarestamultiplicaciondivision1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 30, -1));
        add(jTextField1Numero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 60, -1));

        jLabel1resultado1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1resultado1.setText("=");
        add(jLabel1resultado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, 20));
        add(jTextField1Numero5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 60, -1));
        add(jTextFieldSumarestamultiplicaciondivision2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 30, -1));
        add(jTextField1Numero6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 60, -1));

        jLabel1resultado2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1resultado2.setText("=");
        add(jLabel1resultado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, 20));
        add(jTextField1Resultado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 250, -1));
        add(jTextField1Numero7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 60, -1));
        add(jTextField1Numero8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 60, -1));

        jLabel1resultado3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1resultado3.setText("=");
        add(jLabel1resultado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, 20));
        add(jTextFieldSumarestamultiplicaciondivision3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 30, -1));
        add(jTextField1Resultado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 250, -1));
        add(jTextField1Numero9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 60, -1));
        add(jTextField1Numero10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 60, -1));

        jLabel1resultado4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1resultado4.setText("=");
        add(jLabel1resultado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, 20));
        add(jTextField1Resultado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 250, -1));
        add(jTextFieldSumarestamultiplicaciondivision4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 30, -1));
        add(jTextField1Numero11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 60, -1));
        add(jTextField1Resultado6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 250, -1));
        add(jTextFieldSumarestamultiplicaciondivision5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 30, -1));

        jLabel1resultado5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1resultado5.setText("=");
        add(jLabel1resultado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, 20));
        add(jTextField1Numero12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 60, -1));
        add(jTextField1Resultado7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 310, -1));
        add(jTextField1Numero13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 60, -1));
        add(jTextFieldSumarestamultiplicaciondivision6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 30, -1));
        add(jTextField1Numero14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 60, -1));

        jLabel1resultado6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1resultado6.setText("=");
        add(jLabel1resultado6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, -1, 20));
        add(jTextField1Resultado8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 310, -1));
        add(jTextField1Numero15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 60, -1));
        add(jTextField1Numero16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 60, -1));

        jLabel1resultado7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1resultado7.setText("=");
        add(jLabel1resultado7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, -1, 20));
        add(jTextFieldSumarestamultiplicaciondivision7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 30, -1));
        add(jTextField1Numero17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 60, -1));

        jLabel1resultado8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1resultado8.setText("=");
        add(jLabel1resultado8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, -1, 20));
        add(jTextField1Resultado9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, 310, -1));
        add(jTextFieldSumarestamultiplicaciondivision8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 30, -1));
        add(jTextField1Numero18, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 60, -1));

        jLabel1resultado9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1resultado9.setText("=");
        add(jLabel1resultado9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, -1, 20));
        add(jTextField1Numero19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 60, -1));
        add(jTextFieldSumarestamultiplicaciondivision9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 30, -1));
        add(jTextField1Resultado10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, 310, -1));
        add(jTextField1Numero20, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 60, -1));
        add(jTextField1Resultado11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 310, -1));
        add(jTextField1Numero21, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 60, -1));
        add(jTextField1Numero22, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 60, -1));
        add(jTextFieldSumarestamultiplicaciondivision10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 30, -1));

        jLabel1resultado10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1resultado10.setText("=");
        add(jLabel1resultado10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, -1, 20));
        add(jTextField1Numero23, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 60, -1));
        add(jTextField1Resultado12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 310, -1));

        jLabel1resultado11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1resultado11.setText("=");
        add(jLabel1resultado11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, -1, 20));
        add(jTextField1Numero24, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 60, -1));
        add(jTextFieldSumarestamultiplicaciondivision11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 30, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ComprobarAudios;
    private javax.swing.JLabel jLabel1resultado;
    private javax.swing.JLabel jLabel1resultado1;
    private javax.swing.JLabel jLabel1resultado10;
    private javax.swing.JLabel jLabel1resultado11;
    private javax.swing.JLabel jLabel1resultado2;
    private javax.swing.JLabel jLabel1resultado3;
    private javax.swing.JLabel jLabel1resultado4;
    private javax.swing.JLabel jLabel1resultado5;
    private javax.swing.JLabel jLabel1resultado6;
    private javax.swing.JLabel jLabel1resultado7;
    private javax.swing.JLabel jLabel1resultado8;
    private javax.swing.JLabel jLabel1resultado9;
    private javax.swing.JLabel jLabel2debeaparecer2;
    private javax.swing.JLabel jLabel2debeaparecer3;
    private javax.swing.JTextField jTextField1Numero10;
    private javax.swing.JTextField jTextField1Numero11;
    private javax.swing.JTextField jTextField1Numero12;
    private javax.swing.JTextField jTextField1Numero13;
    private javax.swing.JTextField jTextField1Numero14;
    private javax.swing.JTextField jTextField1Numero15;
    private javax.swing.JTextField jTextField1Numero16;
    private javax.swing.JTextField jTextField1Numero17;
    private javax.swing.JTextField jTextField1Numero18;
    private javax.swing.JTextField jTextField1Numero19;
    private javax.swing.JTextField jTextField1Numero2;
    private javax.swing.JTextField jTextField1Numero20;
    private javax.swing.JTextField jTextField1Numero21;
    private javax.swing.JTextField jTextField1Numero22;
    private javax.swing.JTextField jTextField1Numero23;
    private javax.swing.JTextField jTextField1Numero24;
    private javax.swing.JTextField jTextField1Numero3;
    private javax.swing.JTextField jTextField1Numero4;
    private javax.swing.JTextField jTextField1Numero5;
    private javax.swing.JTextField jTextField1Numero6;
    private javax.swing.JTextField jTextField1Numero7;
    private javax.swing.JTextField jTextField1Numero8;
    private javax.swing.JTextField jTextField1Numero9;
    private javax.swing.JTextField jTextField1PrimerNumero1;
    private javax.swing.JTextField jTextField1Resultado1;
    private javax.swing.JTextField jTextField1Resultado10;
    private javax.swing.JTextField jTextField1Resultado11;
    private javax.swing.JTextField jTextField1Resultado12;
    private javax.swing.JTextField jTextField1Resultado2;
    private javax.swing.JTextField jTextField1Resultado3;
    private javax.swing.JTextField jTextField1Resultado4;
    private javax.swing.JTextField jTextField1Resultado5;
    private javax.swing.JTextField jTextField1Resultado6;
    private javax.swing.JTextField jTextField1Resultado7;
    private javax.swing.JTextField jTextField1Resultado8;
    private javax.swing.JTextField jTextField1Resultado9;
    private javax.swing.JTextField jTextFieldSumarestamultiplicaciondivision;
    private javax.swing.JTextField jTextFieldSumarestamultiplicaciondivision1;
    private javax.swing.JTextField jTextFieldSumarestamultiplicaciondivision10;
    private javax.swing.JTextField jTextFieldSumarestamultiplicaciondivision11;
    private javax.swing.JTextField jTextFieldSumarestamultiplicaciondivision2;
    private javax.swing.JTextField jTextFieldSumarestamultiplicaciondivision3;
    private javax.swing.JTextField jTextFieldSumarestamultiplicaciondivision4;
    private javax.swing.JTextField jTextFieldSumarestamultiplicaciondivision5;
    private javax.swing.JTextField jTextFieldSumarestamultiplicaciondivision6;
    private javax.swing.JTextField jTextFieldSumarestamultiplicaciondivision7;
    private javax.swing.JTextField jTextFieldSumarestamultiplicaciondivision8;
    private javax.swing.JTextField jTextFieldSumarestamultiplicaciondivision9;
    // End of variables declaration//GEN-END:variables
}
