/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_AnimalesdelaSierrainformacion2Unidad2 extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad1U1
     */
    public Vista_AnimalesdelaSierrainformacion2Unidad2() {
        initComponents();
    }

    public JButton getjButton1Continuar() {
        return jButton1Continuar;
    }

    public JLabel getjLabel1mostrar3() {
        return jLabel1mostrar3;
    }

    public JLabel getjLabel1mostrar4() {
        return jLabel1mostrar4;
    }

    public JLabel getjLabel2debeaparecer1() {
        return jLabel2debeaparecer1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2debeaparecer1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1mostrar3 = new javax.swing.JLabel();
        jLabel1mostrar4 = new javax.swing.JLabel();
        jButton1Continuar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2debeaparecer1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2debeaparecer1.setText("KALLARINKAPAK ");
        add(jLabel2debeaparecer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("WIWAKUNAMANTA  \n=  \nSobre los animales  \n\n¡Bienvenido! En esta sección aprenderás \nlos nombres de varios animales en kichwa.  \n\nEl nombre de los animales puede variar según el contexto\ncultural, y también se clasifican como domésticos \no silvestres.\n\nExploraremos juntos animales que viven en la sierra, \ny conoceremos cómo se dicen en kichwa \ny qué función tienen en la vida de las comunidades \nandinas.\n\nAquí tienes una lista de animales con su traducción.  \n\nVamos a colorear los animales domésticos \ncon killu (amarillo) y los silvestres con puka (rojo).\n\nWiwakunata yachaykamaña killu ñawirinawan puka ñawirinawan ch’usaykushun.  \n(Vamos a conocer a los animales usando los colores amarillo y rojo).  \n\n¡Listo! Comencemos con esta colorida aventura 🐾✨\n");
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 320, 330));

        jLabel1mostrar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad2/6.png"))); // NOI18N
        add(jLabel1mostrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        jLabel1mostrar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad2/7.png"))); // NOI18N
        add(jLabel1mostrar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        jButton1Continuar.setBackground(new java.awt.Color(255, 122, 0));
        jButton1Continuar.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        jButton1Continuar.setText("CONTINUAR");
        add(jButton1Continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 610, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad2/Fondo.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-22, -84, 1230, 750));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Continuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1mostrar3;
    private javax.swing.JLabel jLabel1mostrar4;
    private javax.swing.JLabel jLabel2debeaparecer1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
