package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Johnny
 */
public class Vista_Certificado extends javax.swing.JPanel {

    public Vista_Certificado() {
       
        initComponents();
    }

    public JButton getjButton1DescargarCertificado1() {
        return jButton1DescargarCertificado1;
    }

    public JButton getjButton1REENVIARCERTIFICADOALCORREO() {
        return jButton1REENVIARCERTIFICADOALCORREO;
    }

    public JButton getjButton1REENVIARCERTIFICADOALCORREO1() {
        return jButton1REENVIARCERTIFICADOALCORREO1;
    }

    public JButton getjButton1VisualizarCertificado() {
        return jButton1VisualizarCertificado;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjButton1DescargarCertificado1(JButton jButton1DescargarCertificado1) {
        this.jButton1DescargarCertificado1 = jButton1DescargarCertificado1;
    }

    public void setjButton1REENVIARCERTIFICADOALCORREO(JButton jButton1REENVIARCERTIFICADOALCORREO) {
        this.jButton1REENVIARCERTIFICADOALCORREO = jButton1REENVIARCERTIFICADOALCORREO;
    }

    public void setjButton1REENVIARCERTIFICADOALCORREO1(JButton jButton1REENVIARCERTIFICADOALCORREO1) {
        this.jButton1REENVIARCERTIFICADOALCORREO1 = jButton1REENVIARCERTIFICADOALCORREO1;
    }

    public void setjButton1VisualizarCertificado(JButton jButton1VisualizarCertificado) {
        this.jButton1VisualizarCertificado = jButton1VisualizarCertificado;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1REENVIARCERTIFICADOALCORREO = new javax.swing.JButton();
        jButton1DescargarCertificado1 = new javax.swing.JButton();
        jButton1REENVIARCERTIFICADOALCORREO1 = new javax.swing.JButton();
        jButton1VisualizarCertificado = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setPreferredSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Certificado Kwichua (1).png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 18, -1, -1));

        jButton1REENVIARCERTIFICADOALCORREO.setText("REENVIAR CERTIFICADO");
        add(jButton1REENVIARCERTIFICADOALCORREO, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 610, -1, -1));

        jButton1DescargarCertificado1.setText("DESCARGAR CERTIFICADO");
        add(jButton1DescargarCertificado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, -1, -1));

        jButton1REENVIARCERTIFICADOALCORREO1.setText("ENVIAR CERTIFICADO");
        add(jButton1REENVIARCERTIFICADOALCORREO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, -1, -1));

        jButton1VisualizarCertificado.setText("jButton1");
        add(jButton1VisualizarCertificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 23, 800, 560));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1DescargarCertificado1;
    private javax.swing.JButton jButton1REENVIARCERTIFICADOALCORREO;
    private javax.swing.JButton jButton1REENVIARCERTIFICADOALCORREO1;
    private javax.swing.JButton jButton1VisualizarCertificado;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
