/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_Unidad2 extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Unidad1
     */
    public Vista_Unidad2() {
        initComponents();
    }

    public JLabel getFondo() {
        return Fondo;
    }

    public JButton getjButtonAnimales() {
        return jButtonAnimales;
    }

    public JButton getjButtonBack() {
        return jButtonBack;
    }

    public JButton getjButtonEvaluacion() {
        return jButtonEvaluacion;
    }

    public JButton getjButtonFINALIZARUNIDAD1() {
        return jButtonFINALIZARUNIDAD1;
    }

    public JButton getjButtonHistorial() {
        return jButtonHistorial;
    }

    public JButton getjButtonMorfemas() {
        return jButtonMorfemas;
    }

    public JButton getjButtonNumeros() {
        return jButtonNumeros;
    }

    public JButton getjButtonOperaciones() {
        return jButtonOperaciones;
    }

    public JButton getjButtonREINICIARU1() {
        return jButtonREINICIARU1;
    }

    public JProgressBar getjProgressBarUNIDAD1() {
        return jProgressBarUNIDAD2;
    }
    // Actualizar progreso al cargar la vista
    public void actualizarProgreso(int porcentaje) {
    jProgressBarUNIDAD2.setValue(porcentaje);
    jProgressBarUNIDAD2.setString(porcentaje + "%");
    
    // Actualizar estado de botones
    jButtonOperaciones.setEnabled(porcentaje >= 20);
    jButtonAnimales.setEnabled(porcentaje >= 40);
    jButtonMorfemas.setEnabled(porcentaje >= 60);
    jButtonEvaluacion.setEnabled(porcentaje >= 80);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBarUNIDAD2 = new javax.swing.JProgressBar();
        jButtonFINALIZARUNIDAD1 = new javax.swing.JButton();
        jButtonNumeros = new javax.swing.JButton();
        jButtonOperaciones = new javax.swing.JButton();
        jButtonAnimales = new javax.swing.JButton();
        jButtonMorfemas = new javax.swing.JButton();
        jButtonEvaluacion = new javax.swing.JButton();
        jButtonREINICIARU1 = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonHistorial = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setPreferredSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBarUNIDAD2.setBackground(new java.awt.Color(204, 204, 204));
        jProgressBarUNIDAD2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jProgressBarUNIDAD2.setForeground(new java.awt.Color(0, 204, 204));
        jProgressBarUNIDAD2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jProgressBarUNIDAD2.setStringPainted(true);
        add(jProgressBarUNIDAD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 260, 30));

        jButtonFINALIZARUNIDAD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BtnFinalizarU1.png"))); // NOI18N
        add(jButtonFINALIZARUNIDAD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 600, 200, 40));

        jButtonNumeros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SaludosUnidad1.png"))); // NOI18N
        jButtonNumeros.setMaximumSize(new java.awt.Dimension(80, 20));
        jButtonNumeros.setMinimumSize(new java.awt.Dimension(80, 20));
        jButtonNumeros.setPreferredSize(new java.awt.Dimension(80, 20));
        add(jButtonNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 110, 70));

        jButtonOperaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fonologia.png"))); // NOI18N
        jButtonOperaciones.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonOperaciones.setMaximumSize(new java.awt.Dimension(120, 70));
        jButtonOperaciones.setMinimumSize(new java.awt.Dimension(120, 70));
        jButtonOperaciones.setPreferredSize(new java.awt.Dimension(120, 70));
        add(jButtonOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 120, 70));

        jButtonAnimales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PronombresU1.png"))); // NOI18N
        add(jButtonAnimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 120, 70));

        jButtonMorfemas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ActividadU1.png"))); // NOI18N
        add(jButtonMorfemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 120, 70));

        jButtonEvaluacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ActividadU1.png"))); // NOI18N
        jButtonEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEvaluacionActionPerformed(evt);
            }
        });
        add(jButtonEvaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 470, 120, 70));

        jButtonREINICIARU1.setText("Reiniciar");
        add(jButtonREINICIARU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 60, 100, 50));

        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flechaback.png"))); // NOI18N
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 150, 50));

        jButtonHistorial.setText("Ver Historial");
        add(jButtonHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 180, 100, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoUnidad1.jpg"))); // NOI18N
        add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEvaluacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEvaluacionActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Fondo;
    public javax.swing.JButton jButtonAnimales;
    public javax.swing.JButton jButtonBack;
    public javax.swing.JButton jButtonEvaluacion;
    public javax.swing.JButton jButtonFINALIZARUNIDAD1;
    public javax.swing.JButton jButtonHistorial;
    public javax.swing.JButton jButtonMorfemas;
    public javax.swing.JButton jButtonNumeros;
    public javax.swing.JButton jButtonOperaciones;
    public javax.swing.JButton jButtonREINICIARU1;
    public javax.swing.JProgressBar jProgressBarUNIDAD2;
    // End of variables declaration//GEN-END:variables
}
