/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_NumerosUnidad2 extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad1U1
     */
    public Vista_NumerosUnidad2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2debeaparecer1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2debeaparecer1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2debeaparecer1.setText("KALLARINKAPAK ");
        add(jLabel2debeaparecer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("KALLARINKAPAK  \n=  \nPara comenzar  \n\n¡Bienvenido! En esta unidad aprenderás \nsobre los números en kichwa (yupaykuna). \n \nComenzaremos con los números del 1 al 10,\nsu pronunciación y cómo escribirlos correctamente.  \n\nTambién podrás escuchar cómo se dicen los números, \nver ejemplos visuales y practicar con juegos.\n\nVeamos esto para aprender más sobre los números:  \n\nYupaykuna yachankapak kayta rikushun.  \n\n(Vamos a ver esto para aprender los números).  \n\n\n📹 Videos recomendados:  \n\nhttps://www.youtube.com/watch?v=uqotZ0H8Sa8  \n\nhttps://www.youtube.com/watch?v=61CTnmW3ZIC  \n\n¡Listo! Empecemos tu aprendizaje ✨\n");
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 320, 330));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad2/1-100.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesUnidad2/1-20.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2debeaparecer1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
