/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_ActividadAnimalesdelaSierraUnidad2 extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad1U1
     */
    public Vista_ActividadAnimalesdelaSierraUnidad2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2debeaparecer6 = new javax.swing.JLabel();
        jButton1ComprobarAudios = new javax.swing.JButton();
        jLabel2debeaparecer3 = new javax.swing.JLabel();
        jLabel2debeaparecer4 = new javax.swing.JLabel();
        jLabel2debeaparecer5 = new javax.swing.JLabel();
        jTextField1Animalesdosmesticos1 = new javax.swing.JTextField();
        jTextField1animalesdomesticostexto1 = new javax.swing.JTextField();
        jTextField1Animalesdosmesticos2 = new javax.swing.JTextField();
        jTextField1animalesdomesticostexto2 = new javax.swing.JTextField();
        jTextField1Animalesdosmesticos3 = new javax.swing.JTextField();
        jTextField1animalesdomesticostexto3 = new javax.swing.JTextField();
        jTextField1Animalesdosmesticosimagearrastar1 = new javax.swing.JTextField();
        jTextField1animalesdomesticostextoaarrastar2 = new javax.swing.JTextField();
        jTextField1animalesdomesticostextoaarrastar3 = new javax.swing.JTextField();
        jTextField1Animalesdosmesticosimagearrastar2 = new javax.swing.JTextField();
        jTextField1animalesdomesticostextoaarrastar1 = new javax.swing.JTextField();
        jTextField1Animalesdosmesticosimagearrastar3 = new javax.swing.JTextField();
        jTextField1AnimalesSilvestres1 = new javax.swing.JTextField();
        jTextField1animalessilvestres1 = new javax.swing.JTextField();
        jTextField1AnimalesSilvestres2 = new javax.swing.JTextField();
        jTextField1animalessilvestres2 = new javax.swing.JTextField();
        jTextField1AnimalesSilvestres3 = new javax.swing.JTextField();
        jTextField1animalessilvestres3 = new javax.swing.JTextField();
        jTextField1AnimalesSilvestresaarrastar1 = new javax.swing.JTextField();
        jTextField1animalessilvestrestextoaarrastar1 = new javax.swing.JTextField();
        jTextField1AnimalesSilvestresaarrastar2 = new javax.swing.JTextField();
        jTextField1animalessilvestrestextoaarrastar2 = new javax.swing.JTextField();
        jTextField1animalessilvestrestextoaarrastar3 = new javax.swing.JTextField();
        jTextField1AnimalesSilvestresaarrastar3 = new javax.swing.JTextField();
        jButton1CONTINUAR = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2debeaparecer6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2debeaparecer6.setText("Puka (silvestres)");
        add(jLabel2debeaparecer6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, -1, -1));

        jButton1ComprobarAudios.setText("Comprobar");
        add(jButton1ComprobarAudios, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 590, -1, -1));

        jLabel2debeaparecer3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2debeaparecer3.setText("KALLARINKAPAK ");
        add(jLabel2debeaparecer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        jLabel2debeaparecer4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2debeaparecer4.setText("Arrastra y Clasifica");
        add(jLabel2debeaparecer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jLabel2debeaparecer5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2debeaparecer5.setText("Killu (domésticos)");
        add(jLabel2debeaparecer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));
        add(jTextField1Animalesdosmesticos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 120, 100));
        add(jTextField1animalesdomesticostexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 120, -1));
        add(jTextField1Animalesdosmesticos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 120, 100));
        add(jTextField1animalesdomesticostexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 120, -1));
        add(jTextField1Animalesdosmesticos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 120, 100));
        add(jTextField1animalesdomesticostexto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 120, -1));
        add(jTextField1Animalesdosmesticosimagearrastar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 120, 100));
        add(jTextField1animalesdomesticostextoaarrastar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 120, -1));
        add(jTextField1animalesdomesticostextoaarrastar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 120, -1));
        add(jTextField1Animalesdosmesticosimagearrastar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 120, 100));
        add(jTextField1animalesdomesticostextoaarrastar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 120, -1));
        add(jTextField1Animalesdosmesticosimagearrastar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 120, 100));
        add(jTextField1AnimalesSilvestres1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 120, 100));
        add(jTextField1animalessilvestres1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 120, -1));
        add(jTextField1AnimalesSilvestres2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, 120, 100));
        add(jTextField1animalessilvestres2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, 120, -1));
        add(jTextField1AnimalesSilvestres3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 170, 120, 100));
        add(jTextField1animalessilvestres3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 280, 120, -1));
        add(jTextField1AnimalesSilvestresaarrastar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 120, 100));
        add(jTextField1animalessilvestrestextoaarrastar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 120, -1));
        add(jTextField1AnimalesSilvestresaarrastar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 410, 120, 100));
        add(jTextField1animalessilvestrestextoaarrastar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 520, 120, -1));
        add(jTextField1animalessilvestrestextoaarrastar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 550, 120, -1));
        add(jTextField1AnimalesSilvestresaarrastar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 410, 120, 100));

        jButton1CONTINUAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1CONTINUAR.setText("CONTINUAR");
        add(jButton1CONTINUAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 610, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1CONTINUAR;
    private javax.swing.JButton jButton1ComprobarAudios;
    private javax.swing.JLabel jLabel2debeaparecer3;
    private javax.swing.JLabel jLabel2debeaparecer4;
    private javax.swing.JLabel jLabel2debeaparecer5;
    private javax.swing.JLabel jLabel2debeaparecer6;
    private javax.swing.JTextField jTextField1AnimalesSilvestres1;
    private javax.swing.JTextField jTextField1AnimalesSilvestres2;
    private javax.swing.JTextField jTextField1AnimalesSilvestres3;
    private javax.swing.JTextField jTextField1AnimalesSilvestresaarrastar1;
    private javax.swing.JTextField jTextField1AnimalesSilvestresaarrastar2;
    private javax.swing.JTextField jTextField1AnimalesSilvestresaarrastar3;
    private javax.swing.JTextField jTextField1Animalesdosmesticos1;
    private javax.swing.JTextField jTextField1Animalesdosmesticos2;
    private javax.swing.JTextField jTextField1Animalesdosmesticos3;
    private javax.swing.JTextField jTextField1Animalesdosmesticosimagearrastar1;
    private javax.swing.JTextField jTextField1Animalesdosmesticosimagearrastar2;
    private javax.swing.JTextField jTextField1Animalesdosmesticosimagearrastar3;
    private javax.swing.JTextField jTextField1animalesdomesticostexto1;
    private javax.swing.JTextField jTextField1animalesdomesticostexto2;
    private javax.swing.JTextField jTextField1animalesdomesticostexto3;
    private javax.swing.JTextField jTextField1animalesdomesticostextoaarrastar1;
    private javax.swing.JTextField jTextField1animalesdomesticostextoaarrastar2;
    private javax.swing.JTextField jTextField1animalesdomesticostextoaarrastar3;
    private javax.swing.JTextField jTextField1animalessilvestres1;
    private javax.swing.JTextField jTextField1animalessilvestres2;
    private javax.swing.JTextField jTextField1animalessilvestres3;
    private javax.swing.JTextField jTextField1animalessilvestrestextoaarrastar1;
    private javax.swing.JTextField jTextField1animalessilvestrestextoaarrastar2;
    private javax.swing.JTextField jTextField1animalessilvestrestextoaarrastar3;
    // End of variables declaration//GEN-END:variables
}
