/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_ActividadMorfemasUnidad2 extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad1U1
     */
    public Vista_ActividadMorfemasUnidad2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2debeaparecer2 = new javax.swing.JLabel();
        jLabel2TextoMorfemas4 = new javax.swing.JLabel();
        jTextField1TextoMorfemas4 = new javax.swing.JTextField();
        jLabel2TextoMorfemas5 = new javax.swing.JLabel();
        jTextField1TextoMorfemas5 = new javax.swing.JTextField();
        jButton1ComprobarAudios = new javax.swing.JButton();
        jLabel2debeaparecer3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2TextoMorfemas1 = new javax.swing.JLabel();
        jTextField1TextoMorfemas1 = new javax.swing.JTextField();
        jTextField1arrastraropcion1 = new javax.swing.JTextField();
        jLabel2TextoMorfemas2 = new javax.swing.JLabel();
        jTextField1TextoMorfemas2 = new javax.swing.JTextField();
        jTextField1arrastraropcion2 = new javax.swing.JTextField();
        jTextField1TextoMorfemas3 = new javax.swing.JTextField();
        jLabel2TextoMorfemas3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1arrastraropcion3 = new javax.swing.JTextField();
        jTextField1arrastraropcion4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2TextoMorfemas6 = new javax.swing.JLabel();
        jTextField1TextoMorfemas6 = new javax.swing.JTextField();
        jTextField1arrastraropcion5 = new javax.swing.JTextField();
        jLabel2TextoMorfemas7 = new javax.swing.JLabel();
        jTextField1TextoMorfemas7 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2TextoMorfemas8 = new javax.swing.JLabel();
        jTextField1TextoMorfemas8 = new javax.swing.JTextField();
        jLabel2TextoMorfemas9 = new javax.swing.JLabel();
        jTextField1TextoMorfemas9 = new javax.swing.JTextField();
        jTextField1arrastraropcion6 = new javax.swing.JTextField();
        jLabel2TextoMorfemas10 = new javax.swing.JLabel();
        jTextField1TextoMorfemas10 = new javax.swing.JTextField();
        jTextField1arrastraropcion7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField1OPCCIONAARRASTRAR1 = new javax.swing.JTextField();
        jLabel2debeaparecer4 = new javax.swing.JLabel();
        jTextField1OPCCIONAARRASTRAR2 = new javax.swing.JTextField();
        jTextField1OPCCIONAARRASTRAR3 = new javax.swing.JTextField();
        jTextField1OPCCIONAARRASTRAR4 = new javax.swing.JTextField();
        jTextField1OPCCIONAARRASTRAR5 = new javax.swing.JTextField();
        jTextField1OPCCIONAARRASTRAR6 = new javax.swing.JTextField();
        jTextField1OPCCIONAARRASTRAR7 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2debeaparecer2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2debeaparecer2.setText("OPCIONES");
        add(jLabel2debeaparecer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel2TextoMorfemas4.setText("-----------------------");
        add(jLabel2TextoMorfemas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 120, -1));

        jTextField1TextoMorfemas4.setBorder(null);
        add(jTextField1TextoMorfemas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 110, 20));

        jLabel2TextoMorfemas5.setText("-----------------------");
        add(jLabel2TextoMorfemas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 120, -1));

        jTextField1TextoMorfemas5.setBorder(null);
        add(jTextField1TextoMorfemas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 110, 20));

        jButton1ComprobarAudios.setText("Comprobar");
        add(jButton1ComprobarAudios, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, -1, -1));

        jLabel2debeaparecer3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2debeaparecer3.setText("Morfemas");
        add(jLabel2debeaparecer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        jLabel1.setText("4.");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        jLabel2TextoMorfemas1.setText("-----------------------");
        add(jLabel2TextoMorfemas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 120, -1));

        jTextField1TextoMorfemas1.setBorder(null);
        add(jTextField1TextoMorfemas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 110, 20));
        add(jTextField1arrastraropcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 120, -1));

        jLabel2TextoMorfemas2.setText("-----------------------");
        add(jLabel2TextoMorfemas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 120, -1));

        jTextField1TextoMorfemas2.setBorder(null);
        add(jTextField1TextoMorfemas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 110, 20));
        add(jTextField1arrastraropcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 120, -1));

        jTextField1TextoMorfemas3.setBorder(null);
        add(jTextField1TextoMorfemas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 110, 20));

        jLabel2TextoMorfemas3.setText("-----------------------");
        add(jLabel2TextoMorfemas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 120, -1));

        jLabel2.setText("1.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));
        add(jTextField1arrastraropcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 120, -1));
        add(jTextField1arrastraropcion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 120, -1));

        jLabel3.setText("2.");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        jLabel2TextoMorfemas6.setText("-----------------------");
        add(jLabel2TextoMorfemas6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 120, -1));

        jTextField1TextoMorfemas6.setBorder(null);
        add(jTextField1TextoMorfemas6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 110, 20));
        add(jTextField1arrastraropcion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 120, -1));

        jLabel2TextoMorfemas7.setText("-----------------------");
        add(jLabel2TextoMorfemas7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 120, -1));

        jTextField1TextoMorfemas7.setBorder(null);
        add(jTextField1TextoMorfemas7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 110, 20));

        jLabel4.setText("3.");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        jLabel2TextoMorfemas8.setText("-----------------------");
        add(jLabel2TextoMorfemas8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 120, -1));

        jTextField1TextoMorfemas8.setBorder(null);
        add(jTextField1TextoMorfemas8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 110, 20));

        jLabel2TextoMorfemas9.setText("-----------------------");
        add(jLabel2TextoMorfemas9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 120, -1));

        jTextField1TextoMorfemas9.setBorder(null);
        add(jTextField1TextoMorfemas9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 110, 20));
        add(jTextField1arrastraropcion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 120, -1));

        jLabel2TextoMorfemas10.setText("-----------------------");
        add(jLabel2TextoMorfemas10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 120, -1));

        jTextField1TextoMorfemas10.setBorder(null);
        add(jTextField1TextoMorfemas10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 110, 20));
        add(jTextField1arrastraropcion7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 120, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("CONTINUAR");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 610, -1, -1));
        add(jTextField1OPCCIONAARRASTRAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 90, -1));

        jLabel2debeaparecer4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2debeaparecer4.setText("Completa la frase (Con morfemas)");
        add(jLabel2debeaparecer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));
        add(jTextField1OPCCIONAARRASTRAR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, -1));
        add(jTextField1OPCCIONAARRASTRAR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 90, -1));
        add(jTextField1OPCCIONAARRASTRAR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 90, -1));
        add(jTextField1OPCCIONAARRASTRAR5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 90, -1));
        add(jTextField1OPCCIONAARRASTRAR6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 90, -1));
        add(jTextField1OPCCIONAARRASTRAR7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 90, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1ComprobarAudios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2TextoMorfemas1;
    private javax.swing.JLabel jLabel2TextoMorfemas10;
    private javax.swing.JLabel jLabel2TextoMorfemas2;
    private javax.swing.JLabel jLabel2TextoMorfemas3;
    private javax.swing.JLabel jLabel2TextoMorfemas4;
    private javax.swing.JLabel jLabel2TextoMorfemas5;
    private javax.swing.JLabel jLabel2TextoMorfemas6;
    private javax.swing.JLabel jLabel2TextoMorfemas7;
    private javax.swing.JLabel jLabel2TextoMorfemas8;
    private javax.swing.JLabel jLabel2TextoMorfemas9;
    private javax.swing.JLabel jLabel2debeaparecer2;
    private javax.swing.JLabel jLabel2debeaparecer3;
    private javax.swing.JLabel jLabel2debeaparecer4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1OPCCIONAARRASTRAR1;
    private javax.swing.JTextField jTextField1OPCCIONAARRASTRAR2;
    private javax.swing.JTextField jTextField1OPCCIONAARRASTRAR3;
    private javax.swing.JTextField jTextField1OPCCIONAARRASTRAR4;
    private javax.swing.JTextField jTextField1OPCCIONAARRASTRAR5;
    private javax.swing.JTextField jTextField1OPCCIONAARRASTRAR6;
    private javax.swing.JTextField jTextField1OPCCIONAARRASTRAR7;
    private javax.swing.JTextField jTextField1TextoMorfemas1;
    private javax.swing.JTextField jTextField1TextoMorfemas10;
    private javax.swing.JTextField jTextField1TextoMorfemas2;
    private javax.swing.JTextField jTextField1TextoMorfemas3;
    private javax.swing.JTextField jTextField1TextoMorfemas4;
    private javax.swing.JTextField jTextField1TextoMorfemas5;
    private javax.swing.JTextField jTextField1TextoMorfemas6;
    private javax.swing.JTextField jTextField1TextoMorfemas7;
    private javax.swing.JTextField jTextField1TextoMorfemas8;
    private javax.swing.JTextField jTextField1TextoMorfemas9;
    private javax.swing.JTextField jTextField1arrastraropcion1;
    private javax.swing.JTextField jTextField1arrastraropcion2;
    private javax.swing.JTextField jTextField1arrastraropcion3;
    private javax.swing.JTextField jTextField1arrastraropcion4;
    private javax.swing.JTextField jTextField1arrastraropcion5;
    private javax.swing.JTextField jTextField1arrastraropcion6;
    private javax.swing.JTextField jTextField1arrastraropcion7;
    // End of variables declaration//GEN-END:variables
}
