/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_AnimalesdelaSierraUnidad2 extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad1U1
     */
    public Vista_AnimalesdelaSierraUnidad2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2debeaparecer1 = new javax.swing.JLabel();
        jLabel3debeaparecersegundo = new javax.swing.JLabel();
        jLabel1debeaparecercuarto = new javax.swing.JLabel();
        jLabel1debeaparecertercero2 = new javax.swing.JLabel();
        jLabel1debeaparecercdecimo = new javax.swing.JLabel();
        jLabel1debeaparecertercero = new javax.swing.JLabel();
        jLabel1debeaparecercquinto1 = new javax.swing.JLabel();
        jLabel1debeaparecercsexto1 = new javax.swing.JLabel();
        jLabel1debeaparecercseptimo1 = new javax.swing.JLabel();
        jLabel1debeaparecercsoctavo1 = new javax.swing.JLabel();
        jLabel1debeaparecercsonoveno = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2debeaparecer1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2debeaparecer1.setText("ALLI PUNCHA");
        add(jLabel2debeaparecer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel3debeaparecersegundo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3debeaparecersegundo.setText("URKU UYWAKUNA");
        add(jLabel3debeaparecersegundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel1debeaparecercuarto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecercuarto.setText(" si  llegamos a visitar cualquier comunidad no observaremos esta  separación de sexo");
        add(jLabel1debeaparecercuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel1debeaparecertercero2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecertercero2.setText("Animales de la Sierra");
        add(jLabel1debeaparecertercero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel1debeaparecercdecimo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecercdecimo.setText("4.Wakra / toro  ");
        add(jLabel1debeaparecercdecimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 550, 150, 20));

        jLabel1debeaparecertercero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1debeaparecertercero.setText("En el kichwa no existe distinción de masculino y femenino");
        add(jLabel1debeaparecertercero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel1debeaparecercquinto1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1debeaparecercquinto1.setText(" Sin embargo, ahora se ha plantado el uso de las  palabras warmi y kari para separar por género");
        add(jLabel1debeaparecercquinto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        jLabel1debeaparecercsexto1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecercsexto1.setText("Es decir: ");
        add(jLabel1debeaparecercsexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, -1, -1));

        jLabel1debeaparecercseptimo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecercseptimo1.setText("1.Warmi / femenino");
        add(jLabel1debeaparecercseptimo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 150, 20));

        jLabel1debeaparecercsoctavo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecercsoctavo1.setText("2.Kari / masculino ");
        add(jLabel1debeaparecercsoctavo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 140, 20));

        jLabel1debeaparecercsonoveno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecercsonoveno.setText("3.Warmi wakra / vaca  ");
        add(jLabel1debeaparecercsonoveno, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, 170, 20));

        jButton1.setText("CONTINUAR");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 620, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1debeaparecercdecimo;
    private javax.swing.JLabel jLabel1debeaparecercquinto1;
    private javax.swing.JLabel jLabel1debeaparecercseptimo1;
    private javax.swing.JLabel jLabel1debeaparecercsexto1;
    private javax.swing.JLabel jLabel1debeaparecercsoctavo1;
    private javax.swing.JLabel jLabel1debeaparecercsonoveno;
    private javax.swing.JLabel jLabel1debeaparecercuarto;
    private javax.swing.JLabel jLabel1debeaparecertercero;
    private javax.swing.JLabel jLabel1debeaparecertercero2;
    private javax.swing.JLabel jLabel2debeaparecer1;
    private javax.swing.JLabel jLabel3debeaparecersegundo;
    // End of variables declaration//GEN-END:variables
}
