/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_AnimalesdelaSierraUnidad2 extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad1U1
     */
    public Vista_AnimalesdelaSierraUnidad2() {
        initComponents();
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public JLabel getjLabel1debeaparecercdecimo() {
        return jLabel1debeaparecercdecimo;
    }

    public JLabel getjLabel1debeaparecercquinto1() {
        return jLabel1debeaparecercquinto1;
    }

    public JLabel getjLabel1debeaparecercseptimo1() {
        return jLabel1debeaparecercseptimo1;
    }

    public JLabel getjLabel1debeaparecercsexto1() {
        return jLabel1debeaparecercsexto1;
    }

    public JLabel getjLabel1debeaparecercsoctavo1() {
        return jLabel1debeaparecercsoctavo1;
    }

    public JLabel getjLabel1debeaparecercsonoveno() {
        return jLabel1debeaparecercsonoveno;
    }

    public JLabel getjLabel1debeaparecercuarto() {
        return jLabel1debeaparecercuarto;
    }

    public JLabel getjLabel1debeaparecertercero() {
        return jLabel1debeaparecertercero;
    }

    public JLabel getjLabel1debeaparecertercero2() {
        return jLabel1debeaparecertercero2;
    }

    public JLabel getjLabel2debeaparecer1() {
        return jLabel2debeaparecer1;
    }

    public JLabel getjLabel3debeaparecersegundo() {
        return jLabel3debeaparecersegundo;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public void setjLabel1debeaparecercdecimo(JLabel jLabel1debeaparecercdecimo) {
        this.jLabel1debeaparecercdecimo = jLabel1debeaparecercdecimo;
    }

    public void setjLabel1debeaparecercquinto1(JLabel jLabel1debeaparecercquinto1) {
        this.jLabel1debeaparecercquinto1 = jLabel1debeaparecercquinto1;
    }

    public void setjLabel1debeaparecercseptimo1(JLabel jLabel1debeaparecercseptimo1) {
        this.jLabel1debeaparecercseptimo1 = jLabel1debeaparecercseptimo1;
    }

    public void setjLabel1debeaparecercsexto1(JLabel jLabel1debeaparecercsexto1) {
        this.jLabel1debeaparecercsexto1 = jLabel1debeaparecercsexto1;
    }

    public void setjLabel1debeaparecercsoctavo1(JLabel jLabel1debeaparecercsoctavo1) {
        this.jLabel1debeaparecercsoctavo1 = jLabel1debeaparecercsoctavo1;
    }

    public void setjLabel1debeaparecercsonoveno(JLabel jLabel1debeaparecercsonoveno) {
        this.jLabel1debeaparecercsonoveno = jLabel1debeaparecercsonoveno;
    }

    public void setjLabel1debeaparecercuarto(JLabel jLabel1debeaparecercuarto) {
        this.jLabel1debeaparecercuarto = jLabel1debeaparecercuarto;
    }

    public void setjLabel1debeaparecertercero(JLabel jLabel1debeaparecertercero) {
        this.jLabel1debeaparecertercero = jLabel1debeaparecertercero;
    }

    public void setjLabel1debeaparecertercero2(JLabel jLabel1debeaparecertercero2) {
        this.jLabel1debeaparecertercero2 = jLabel1debeaparecertercero2;
    }

    public void setjLabel2debeaparecer1(JLabel jLabel2debeaparecer1) {
        this.jLabel2debeaparecer1 = jLabel2debeaparecer1;
    }

    public void setjLabel3debeaparecersegundo(JLabel jLabel3debeaparecersegundo) {
        this.jLabel3debeaparecersegundo = jLabel3debeaparecersegundo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2debeaparecer1 = new javax.swing.JLabel();
        jLabel3debeaparecersegundo = new javax.swing.JLabel();
        jLabel1debeaparecercuarto = new javax.swing.JLabel();
        jLabel1debeaparecertercero2 = new javax.swing.JLabel();
        jLabel1debeaparecercdecimo = new javax.swing.JLabel();
        jLabel1debeaparecertercero = new javax.swing.JLabel();
        jLabel1debeaparecercquinto1 = new javax.swing.JLabel();
        jLabel1debeaparecercsexto1 = new javax.swing.JLabel();
        jLabel1debeaparecercseptimo1 = new javax.swing.JLabel();
        jLabel1debeaparecercsoctavo1 = new javax.swing.JLabel();
        jLabel1debeaparecercsonoveno = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2debeaparecer1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2debeaparecer1.setText("ALLI PUNCHA");
        add(jLabel2debeaparecer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel3debeaparecersegundo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3debeaparecersegundo.setText("URKU UYWAKUNA");
        add(jLabel3debeaparecersegundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel1debeaparecercuarto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecercuarto.setText(" si  llegamos a visitar cualquier comunidad no observaremos esta  separación de sexo");
        add(jLabel1debeaparecercuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel1debeaparecertercero2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecertercero2.setText("Animales de la Sierra");
        add(jLabel1debeaparecertercero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel1debeaparecercdecimo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecercdecimo.setText("4.Wakra / toro  ");
        add(jLabel1debeaparecercdecimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 550, 150, 20));

        jLabel1debeaparecertercero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1debeaparecertercero.setText("En el kichwa no existe distinción de masculino y femenino");
        add(jLabel1debeaparecertercero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel1debeaparecercquinto1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1debeaparecercquinto1.setText(" Sin embargo, ahora se ha plantado el uso de las  palabras warmi y kari para separar por género");
        add(jLabel1debeaparecercquinto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        jLabel1debeaparecercsexto1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecercsexto1.setText("Es decir: ");
        add(jLabel1debeaparecercsexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, -1, -1));

        jLabel1debeaparecercseptimo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecercseptimo1.setText("1.Warmi / femenino");
        add(jLabel1debeaparecercseptimo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 150, 20));

        jLabel1debeaparecercsoctavo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecercsoctavo1.setText("2.Kari / masculino ");
        add(jLabel1debeaparecercsoctavo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 140, 20));

        jLabel1debeaparecercsonoveno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1debeaparecercsonoveno.setText("3.Warmi wakra / vaca  ");
        add(jLabel1debeaparecercsonoveno, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, 170, 20));

        jButton1.setText("CONTINUAR");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 620, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1debeaparecercdecimo;
    private javax.swing.JLabel jLabel1debeaparecercquinto1;
    private javax.swing.JLabel jLabel1debeaparecercseptimo1;
    private javax.swing.JLabel jLabel1debeaparecercsexto1;
    private javax.swing.JLabel jLabel1debeaparecercsoctavo1;
    private javax.swing.JLabel jLabel1debeaparecercsonoveno;
    private javax.swing.JLabel jLabel1debeaparecercuarto;
    private javax.swing.JLabel jLabel1debeaparecertercero;
    private javax.swing.JLabel jLabel1debeaparecertercero2;
    private javax.swing.JLabel jLabel2debeaparecer1;
    private javax.swing.JLabel jLabel3debeaparecersegundo;
    // End of variables declaration//GEN-END:variables
}
