/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_EvaluacionU2 extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad1U1
     */
    public Vista_EvaluacionU2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1ComprobaryFinalizarUnidad = new javax.swing.JButton();
        jLabel2debeaparecer3 = new javax.swing.JLabel();
        jLabel2debeaparecer4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1Pregunta1 = new javax.swing.JLabel();
        jRadioButtonSeleccionelnombrecorrectodelanimalopcion1 = new javax.swing.JRadioButton();
        jRadioButtonOpcion1 = new javax.swing.JRadioButton();
        jRadioButtonOpcion2 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel1SegundaPregunta = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel1Pregunta3darunaimagendeunanimalalzar = new javax.swing.JLabel();
        MostrarImagendeunAnimal = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButtonSeleccionelnombrecorrectodelanimalopcion2 = new javax.swing.JRadioButton();
        jRadioButtonSeleccionelnombrecorrectodelanimalopcion3 = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Pregunta4Completarlafrase = new javax.swing.JLabel();
        jLabel2TextoMorfemas1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1TextoMorfemas1 = new javax.swing.JTextField();
        jTextField1arrastraropcion2 = new javax.swing.JTextField();
        jLabel2TextoMorfemas5 = new javax.swing.JLabel();
        jLabel2TextoMorfemas4 = new javax.swing.JLabel();
        jTextField1TextoMorfemas2 = new javax.swing.JTextField();
        jTextField1arrastraropcion3 = new javax.swing.JTextField();
        jTextField1TextoMorfemas4 = new javax.swing.JTextField();
        jTextField1OPCCIONAARRASTRAR2 = new javax.swing.JTextField();
        jTextField1OPCCIONAARRASTRAR3 = new javax.swing.JTextField();
        jTextField1OPCCIONAARRASTRAR4 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1ComprobaryFinalizarUnidad.setText("Comprobar");
        add(jButton1ComprobaryFinalizarUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 620, -1, -1));

        jLabel2debeaparecer3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2debeaparecer3.setText("EVALUCION");
        add(jLabel2debeaparecer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        jLabel2debeaparecer4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2debeaparecer4.setText("Prueba tus conocimientos");
        add(jLabel2debeaparecer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        jButton1.setText("Regresar");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, -1, -1));

        jScrollPane1.setViewportView(jLabel1Pregunta1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 370, 20));

        jRadioButtonSeleccionelnombrecorrectodelanimalopcion1.setText("jRadioButton1");
        add(jRadioButtonSeleccionelnombrecorrectodelanimalopcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, -1));

        jRadioButtonOpcion1.setText("jRadioButton1");
        add(jRadioButtonOpcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        jRadioButtonOpcion2.setText("jRadioButton1");
        add(jRadioButtonOpcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        jScrollPane2.setViewportView(jLabel1SegundaPregunta);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 370, 20));

        jRadioButton2.setText("jRadioButton1");
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        jRadioButton3.setText("jRadioButton1");
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        jRadioButton4.setText("jRadioButton1");
        add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));

        jScrollPane3.setViewportView(jLabel1Pregunta3darunaimagendeunanimalalzar);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 370, 20));

        MostrarImagendeunAnimal.setText("jLabel1");
        add(MostrarImagendeunAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 110, 90));

        jRadioButton5.setText("jRadioButton1");
        add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, -1, -1));

        jRadioButtonSeleccionelnombrecorrectodelanimalopcion2.setText("jRadioButton1");
        add(jRadioButtonSeleccionelnombrecorrectodelanimalopcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, -1, -1));

        jRadioButtonSeleccionelnombrecorrectodelanimalopcion3.setText("jRadioButton1");
        add(jRadioButtonSeleccionelnombrecorrectodelanimalopcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        jScrollPane4.setViewportView(Pregunta4Completarlafrase);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 380, 20));

        jLabel2TextoMorfemas1.setText("-----------------------");
        add(jLabel2TextoMorfemas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 120, -1));

        jLabel2.setText("1.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        jTextField1TextoMorfemas1.setBorder(null);
        add(jTextField1TextoMorfemas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 110, 20));
        add(jTextField1arrastraropcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 120, -1));

        jLabel2TextoMorfemas5.setText("-----------------------");
        add(jLabel2TextoMorfemas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 120, -1));

        jLabel2TextoMorfemas4.setText("-----------------------");
        add(jLabel2TextoMorfemas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, 120, -1));

        jTextField1TextoMorfemas2.setBorder(null);
        add(jTextField1TextoMorfemas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 110, 20));
        add(jTextField1arrastraropcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 120, -1));

        jTextField1TextoMorfemas4.setBorder(null);
        add(jTextField1TextoMorfemas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 110, 20));
        add(jTextField1OPCCIONAARRASTRAR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 90, -1));
        add(jTextField1OPCCIONAARRASTRAR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 90, -1));
        add(jTextField1OPCCIONAARRASTRAR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 90, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MostrarImagendeunAnimal;
    private javax.swing.JLabel Pregunta4Completarlafrase;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1ComprobaryFinalizarUnidad;
    private javax.swing.JLabel jLabel1Pregunta1;
    private javax.swing.JLabel jLabel1Pregunta3darunaimagendeunanimalalzar;
    private javax.swing.JLabel jLabel1SegundaPregunta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2TextoMorfemas1;
    private javax.swing.JLabel jLabel2TextoMorfemas4;
    private javax.swing.JLabel jLabel2TextoMorfemas5;
    private javax.swing.JLabel jLabel2debeaparecer3;
    private javax.swing.JLabel jLabel2debeaparecer4;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButtonOpcion1;
    private javax.swing.JRadioButton jRadioButtonOpcion2;
    private javax.swing.JRadioButton jRadioButtonSeleccionelnombrecorrectodelanimalopcion1;
    private javax.swing.JRadioButton jRadioButtonSeleccionelnombrecorrectodelanimalopcion2;
    private javax.swing.JRadioButton jRadioButtonSeleccionelnombrecorrectodelanimalopcion3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1OPCCIONAARRASTRAR2;
    private javax.swing.JTextField jTextField1OPCCIONAARRASTRAR3;
    private javax.swing.JTextField jTextField1OPCCIONAARRASTRAR4;
    private javax.swing.JTextField jTextField1TextoMorfemas1;
    private javax.swing.JTextField jTextField1TextoMorfemas2;
    private javax.swing.JTextField jTextField1TextoMorfemas4;
    private javax.swing.JTextField jTextField1arrastraropcion2;
    private javax.swing.JTextField jTextField1arrastraropcion3;
    // End of variables declaration//GEN-END:variables
}
