/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VistasUnidad3;

import Vista.*;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_Leccion_Familia extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad1U1
     */
    public Vista_Leccion_Familia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2debeaparecer1 = new javax.swing.JLabel();
        abuela = new javax.swing.JLabel();
        mama = new javax.swing.JLabel();
        papa = new javax.swing.JLabel();
        hijo = new javax.swing.JLabel();
        abuelo = new javax.swing.JLabel();
        yo = new javax.swing.JLabel();
        hija = new javax.swing.JLabel();
        hermano = new javax.swing.JLabel();
        hermana = new javax.swing.JLabel();
        tia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2debeaparecer1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2debeaparecer1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2debeaparecer1.setText("FAMILIA ( AYLLU )");
        add(jLabel2debeaparecer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        abuela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        abuela.setForeground(new java.awt.Color(0, 0, 0));
        abuela.setText("<html><center>ABUELA<br>HATUN MAMA<center></html>");
        abuela.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        abuela.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(abuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, -1, -1));

        mama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mama.setForeground(new java.awt.Color(0, 0, 0));
        mama.setText("<html><center>MAMÁ<br>MAMA<center></html>");
        add(mama, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, -1, -1));

        papa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        papa.setForeground(new java.awt.Color(0, 0, 0));
        papa.setText("<html><center>PAPÁ<br>TAYTA<center></html>");
        add(papa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 340, -1, -1));

        hijo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hijo.setForeground(new java.awt.Color(0, 0, 0));
        hijo.setText("<html><center>HIJO<br>CHURI\n<center></html>");
        add(hijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 360, -1, -1));

        abuelo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        abuelo.setForeground(new java.awt.Color(0, 0, 0));
        abuelo.setText("<html><center>ABUELO<br>HATUN TAYTA<center></html>");
        add(abuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, -1, -1));

        yo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        yo.setForeground(new java.awt.Color(0, 0, 0));
        yo.setText("<html><center>ÑUKA<br> YO<center></html>");
        add(yo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 470, -1, -1));

        hija.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hija.setForeground(new java.awt.Color(0, 0, 0));
        hija.setText("<html><center>HIJA<br>USHI <center></html>");
        add(hija, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 360, -1, -1));

        hermano.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hermano.setForeground(new java.awt.Color(0, 0, 0));
        hermano.setText("<html><center>HERMANO<br> WAWKI-TURI<center></html>");
        add(hermano, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, -1, -1));

        hermana.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hermana.setForeground(new java.awt.Color(0, 0, 0));
        hermana.setText("<html><center>HERMANA<br>ÑAÑA-PANI<center></html>");
        add(hermana, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 470, -1, -1));

        tia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tia.setForeground(new java.awt.Color(0, 0, 0));
        tia.setText("<html><center>TIA<br>TIYU MAMA<center></html>");
        add(tia, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 600, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("<html><center>TIO<br>TIYU TAYTA\n<center></html>");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 600, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lecciones/Familia.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, 560));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<html><center>COMPLETAR<br>LECCION<center></html>");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 180, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("<html><center>En el kichwa, las palabras cambian de acuerdo a su género. <br><br> Churi / Hijo<br> Ushi / Hija<br> Wawki / Hermano, pero entre hermanos<br> Turi / hermano, pero de hermana a hermano<br> Pani / Hermana, hombre mujer<br> Ñaña / entre mujeres<center></html>");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 430, 540));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lbl.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 660));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abuela;
    private javax.swing.JLabel abuelo;
    private javax.swing.JLabel hermana;
    private javax.swing.JLabel hermano;
    private javax.swing.JLabel hija;
    private javax.swing.JLabel hijo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2debeaparecer1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel mama;
    private javax.swing.JLabel papa;
    private javax.swing.JLabel tia;
    private javax.swing.JLabel yo;
    // End of variables declaration//GEN-END:variables
}
