package Vista.Admin;

import com.toedter.calendar.JDateChooser;
import java.awt.Dimension;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author Bryan
 */
public class Graficos extends javax.swing.JPanel {

    /**
     * Creates new form Graficos
     */
    public Graficos() {
        initComponents();
        PanelGraficos.setLayout(new java.awt.BorderLayout());
        PanelGraficos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelGraficos.setBackground(new java.awt.Color(255, 255, 255));
    }

    public JPanel getPanelGraficos() {
        return PanelGraficos;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public JComboBox<String> getjComboBox1() {
        return comboBoxFiltro;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JRadioButton getRdAreas() {
        return rdAreas;
    }

    public JRadioButton getRdBarras() {
        return rdBarras;
    }

    public JRadioButton getRdPastel() {
        return rdPastel;
    }

    public JDateChooser getjDateChooserDesde() {
        return jDateChooserDesde;
    }

    public JDateChooser getjDateChooserHasta() {
        return jDateChooserHasta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelGraficos = new javax.swing.JPanel();
        comboBoxFiltro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        rdBarras = new javax.swing.JRadioButton();
        rdPastel = new javax.swing.JRadioButton();
        rdAreas = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jDateChooserDesde = new com.toedter.calendar.JDateChooser();
        jDateChooserHasta = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(235, 243, 250));

        PanelGraficos.setBackground(new java.awt.Color(255, 255, 255));
        PanelGraficos.setMaximumSize(new java.awt.Dimension(1190, 600));
        PanelGraficos.setMinimumSize(new java.awt.Dimension(1190, 600));

        javax.swing.GroupLayout PanelGraficosLayout = new javax.swing.GroupLayout(PanelGraficos);
        PanelGraficos.setLayout(PanelGraficosLayout);
        PanelGraficosLayout.setHorizontalGroup(
            PanelGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelGraficosLayout.setVerticalGroup(
            PanelGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        comboBoxFiltro.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        comboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registros de usuarios", "Actividad por unidad", "Progreso completado", "Resultados de evaluaciones", "Usuarios inactivos" }));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel1.setText("Filtrar por:");

        buttonGroup1.add(rdBarras);
        rdBarras.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        rdBarras.setText("Barras");

        buttonGroup1.add(rdPastel);
        rdPastel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        rdPastel.setText("Pastel");

        buttonGroup1.add(rdAreas);
        rdAreas.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        rdAreas.setText("Areas");

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel2.setText("Tipo de grafico:");

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel3.setText("Filtrar por fecha desde:");

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel5.setText("Hasta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(PanelGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdBarras)
                        .addGap(33, 33, 33)
                        .addComponent(rdPastel)
                        .addGap(29, 29, 29)
                        .addComponent(rdAreas)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooserHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(rdBarras)
                    .addComponent(rdPastel)
                    .addComponent(rdAreas)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooserDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(19, 19, 19)
                .addComponent(PanelGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanelGraficos;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> comboBoxFiltro;
    public com.toedter.calendar.JDateChooser jDateChooserDesde;
    public com.toedter.calendar.JDateChooser jDateChooserHasta;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JRadioButton rdAreas;
    public javax.swing.JRadioButton rdBarras;
    public javax.swing.JRadioButton rdPastel;
    // End of variables declaration//GEN-END:variables
}
