package Vista.Admin;

import com.toedter.calendar.JDateChooser;
import java.awt.Dimension;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author Bryan
 */
public class Graficos extends javax.swing.JPanel {

    /**
     * Creates new form Graficos
     */
    public Graficos() {
        initComponents();
        PanelGraficos.setLayout(new java.awt.BorderLayout());
        PanelGraficos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelGraficos.setBackground(new java.awt.Color(255, 255, 255));
    }

    public JPanel getPanelGraficos() {
        return PanelGraficos;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public JComboBox<String> getjComboBox1() {
        return comboBoxFiltro;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JRadioButton getRdAreas() {
        return rdAreas;
    }

    public JRadioButton getRdBarras() {
        return rdBarras;
    }

    public JRadioButton getRdPastel() {
        return rdPastel;
    }

    public JDateChooser getjDateChooserDesde() {
        return jDateChooserDesde;
    }

    public JDateChooser getjDateChooserHasta() {
        return jDateChooserHasta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelGraficos = new javax.swing.JPanel();
        comboBoxFiltro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        rdBarras = new javax.swing.JRadioButton();
        rdPastel = new javax.swing.JRadioButton();
        rdAreas = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jDateChooserDesde = new com.toedter.calendar.JDateChooser();
        jDateChooserHasta = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(200, 225, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelGraficos.setBackground(new java.awt.Color(255, 255, 255));
        PanelGraficos.setMaximumSize(new java.awt.Dimension(1190, 600));
        PanelGraficos.setMinimumSize(new java.awt.Dimension(1190, 600));
        PanelGraficos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(PanelGraficos, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 110, 1150, 525));

        comboBoxFiltro.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        comboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registros de usuarios", "Actividad por unidad", "Progreso completado", "Resultados de evaluaciones", "Usuarios inactivos" }));
        add(comboBoxFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 20, 374, -1));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Filtrar por:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 21, -1, -1));

        buttonGroup1.add(rdBarras);
        rdBarras.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        rdBarras.setForeground(new java.awt.Color(255, 255, 255));
        rdBarras.setText("Barras");
        add(rdBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 21, -1, -1));

        buttonGroup1.add(rdPastel);
        rdPastel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        rdPastel.setForeground(new java.awt.Color(255, 255, 255));
        rdPastel.setText("Pastel");
        add(rdPastel, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 21, -1, -1));

        buttonGroup1.add(rdAreas);
        rdAreas.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        rdAreas.setForeground(new java.awt.Color(255, 255, 255));
        rdAreas.setText("Areas");
        add(rdAreas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1059, 21, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo de grafico:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 21, -1, -1));
        add(jDateChooserDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 69, 150, -1));
        add(jDateChooserHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 69, 150, -1));

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Filtrar por fecha desde:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 69, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoooo12.jpg"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(1190, 110));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 660));

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel5.setText("Hasta:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 69, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanelGraficos;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> comboBoxFiltro;
    public com.toedter.calendar.JDateChooser jDateChooserDesde;
    public com.toedter.calendar.JDateChooser jDateChooserHasta;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JRadioButton rdAreas;
    public javax.swing.JRadioButton rdBarras;
    public javax.swing.JRadioButton rdPastel;
    // End of variables declaration//GEN-END:variables
}
