package VistasUnidad4;

import VistasUnidad3.*;
import Vista.*;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_Actividad_PartesCuerpo extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad1U1
     */
    public Vista_Actividad_PartesCuerpo() {
        initComponents();
    }

    public JButton getCompletarActividad() {
        return CompletarActividad;
    }

    public JTextField getCabeza() {
        return cabeza;
    }

    public JTextField getCuello() {
        return cuello;
    }

    public JTextField getEstomago() {
        return estomago;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2debeaparecer1() {
        return jLabel2debeaparecer1;
    }

    public JTextField getMano() {
        return mano;
    }

    public JTextField getMejilla() {
        return mejilla;
    }

    public JTextField getPecho() {
        return pecho;
    }

    public JTextField getPie() {
        return pie;
    }

    public JTextField getPierna() {
        return pierna;
    }

    public JTextField getRodilla() {
        return rodilla;
    }

    public JTextField getTobillo() {
        return tobillo;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2debeaparecer1 = new javax.swing.JLabel();
        CompletarActividad = new javax.swing.JButton();
        mejilla = new javax.swing.JTextField();
        cabeza = new javax.swing.JTextField();
        cuello = new javax.swing.JTextField();
        mano = new javax.swing.JTextField();
        rodilla = new javax.swing.JTextField();
        pie = new javax.swing.JTextField();
        tobillo = new javax.swing.JTextField();
        pierna = new javax.swing.JTextField();
        estomago = new javax.swing.JTextField();
        pecho = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2debeaparecer1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2debeaparecer1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2debeaparecer1.setText("Escribe como se escriben estas partes del cuerpo en kiwcha");
        add(jLabel2debeaparecer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        CompletarActividad.setBackground(new java.awt.Color(255, 102, 0));
        CompletarActividad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CompletarActividad.setForeground(new java.awt.Color(255, 255, 255));
        CompletarActividad.setText("<html><center>COMPLETAR<br>ACTIVIDAD<center></html>");
        add(CompletarActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 600, 180, -1));
        add(mejilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 220, 40));

        cabeza.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cabeza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cabezaActionPerformed(evt);
            }
        });
        add(cabeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 220, 40));
        add(cuello, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 220, 40));
        add(mano, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 220, 40));
        add(rodilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 220, 40));
        add(pie, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 220, 40));
        add(tobillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 220, 40));
        add(pierna, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 220, 40));
        add(estomago, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 220, 40));
        add(pecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 220, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lecciones/partesCuerpo.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 800, 457));
    }// </editor-fold>//GEN-END:initComponents

    private void cabezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cabezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cabezaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton CompletarActividad;
    public javax.swing.JTextField cabeza;
    public javax.swing.JTextField cuello;
    public javax.swing.JTextField estomago;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2debeaparecer1;
    public javax.swing.JTextField mano;
    public javax.swing.JTextField mejilla;
    public javax.swing.JTextField pecho;
    public javax.swing.JTextField pie;
    public javax.swing.JTextField pierna;
    public javax.swing.JTextField rodilla;
    public javax.swing.JTextField tobillo;
    // End of variables declaration//GEN-END:variables
}
