package VistasUnidad4;

import VistasUnidad3.*;
import Vista.*;
import javax.swing.JButton;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_Leccion_PartesCuerpo extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad1U1
     */
    public Vista_Leccion_PartesCuerpo() {
        initComponents();
    }

    public JButton getCompletarLeccion() {
        return CompletarLeccion;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2debeaparecer1 = new javax.swing.JLabel();
        CompletarLeccion = new javax.swing.JButton();
        jLabel2debeaparecer2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2debeaparecer1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2debeaparecer1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2debeaparecer1.setText("<html><center>Aqui veremos las partes del cuerpo humano y como se escriben en kiwcha.<center></html>");
        add(jLabel2debeaparecer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 370, 220));

        CompletarLeccion.setBackground(new java.awt.Color(255, 102, 0));
        CompletarLeccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CompletarLeccion.setForeground(new java.awt.Color(255, 255, 255));
        CompletarLeccion.setText("<html><center>COMPLETAR<br>ACTIVIDAD<center></html>");
        add(CompletarLeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 210, -1));

        jLabel2debeaparecer2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2debeaparecer2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2debeaparecer2.setText("CUERPO HUMANO (RURASHUN)");
        add(jLabel2debeaparecer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lecciones/cuerpohumano.jpg"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 593, 641));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton CompletarLeccion;
    public javax.swing.JLabel jLabel2debeaparecer1;
    public javax.swing.JLabel jLabel2debeaparecer2;
    public javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
