package VistasUnidad4;

import VistasUnidad3.*;
import Vista.*;
import javax.swing.JButton;
import javax.swing.JLabel;


public class Vista_Leccion_Colores extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad1U1
     */
    public Vista_Leccion_Colores() {
        initComponents();
    }

    public JButton getCompletarLeccion() {
        return CompletarLeccion;
    }

    public JLabel getAbuela() {
        return abuela;
    }

    public JLabel getAbuelo() {
        return abuelo;
    }

    public JLabel getHermana() {
        return hermana;
    }

    public JLabel getHermano() {
        return hermano;
    }

    public JLabel getHijo() {
        return hijo;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel2debeaparecer1() {
        return jLabel2debeaparecer1;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getMama() {
        return mama;
    }

    public JLabel getPapa() {
        return papa;
    }

    public JLabel getTia() {
        return tia;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2debeaparecer1 = new javax.swing.JLabel();
        abuela = new javax.swing.JLabel();
        mama = new javax.swing.JLabel();
        papa = new javax.swing.JLabel();
        hijo = new javax.swing.JLabel();
        abuelo = new javax.swing.JLabel();
        hermano = new javax.swing.JLabel();
        hermana = new javax.swing.JLabel();
        tia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CompletarLeccion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2debeaparecer1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2debeaparecer1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2debeaparecer1.setText("COLORES ( TULLPUKUNA )");
        add(jLabel2debeaparecer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        abuela.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        abuela.setForeground(new java.awt.Color(255, 255, 255));
        abuela.setText("<html><center>AZUL<br>ANKAS<center></html>");
        abuela.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        abuela.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(abuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, -1, -1));

        mama.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mama.setForeground(new java.awt.Color(255, 255, 255));
        mama.setText("<html><center>VERDE<br>WAYLLA<center></html>");
        add(mama, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, -1, -1));

        papa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        papa.setForeground(new java.awt.Color(255, 255, 255));
        papa.setText("<html><center>NARANJA<br>KISHPU<center></html>");
        add(papa, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 290, -1, -1));

        hijo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hijo.setForeground(new java.awt.Color(255, 255, 255));
        hijo.setText("<html><center>NEGRO<br>YANA\n<center></html>");
        add(hijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 370, -1, -1));

        abuelo.setBackground(new java.awt.Color(0, 0, 0));
        abuelo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        abuelo.setForeground(new java.awt.Color(255, 255, 255));
        abuelo.setText("<html><center>AMARILLO<br>KILLU<center></html>");
        add(abuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, -1, -1));

        hermano.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hermano.setForeground(new java.awt.Color(255, 255, 255));
        hermano.setText("<html><center>MORADO<br> MAYWA<center></html>");
        add(hermano, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, -1, -1));

        hermana.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hermana.setForeground(new java.awt.Color(0, 0, 0));
        hermana.setText("<html><center>BLANCO<br>YURAK<center></html>");
        add(hermana, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 130, -1, -1));

        tia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tia.setForeground(new java.awt.Color(0, 0, 0));
        tia.setText("<html><center>TIA<br>TIYU MAMA<center></html>");
        add(tia, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html><center>ROJO<br>PUKA\n<center></html>");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 490, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lecciones/Colores.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 590, 560));

        CompletarLeccion.setBackground(new java.awt.Color(255, 102, 0));
        CompletarLeccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CompletarLeccion.setForeground(new java.awt.Color(255, 255, 255));
        CompletarLeccion.setText("<html><center>COMPLETAR<br>LECCION<center></html>");
        add(CompletarLeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 180, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("<html><center>Cuando queremos decir que un color es más claro, usamos la palabra “chawa” antes del color.\nPor ejemplo: chawa puka significa “rojo claro”.<br><br>\n\nPara decir que un color es más oscuro, usamos la palabra “yanalla” antes del color.\nPor ejemplo: yanalla ankash significa “azul oscuro”.<center></html>");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 430, 500));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lbl.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 660));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton CompletarLeccion;
    public javax.swing.JLabel abuela;
    public javax.swing.JLabel abuelo;
    public javax.swing.JLabel hermana;
    public javax.swing.JLabel hermano;
    public javax.swing.JLabel hijo;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel2debeaparecer1;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel mama;
    public javax.swing.JLabel papa;
    public javax.swing.JLabel tia;
    // End of variables declaration//GEN-END:variables
}
