package VistasUnidad4;

import VistasUnidad3.*;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;


/**
 *
 * @author Jhony Espinoza
 */
public class Vista_Actividad_Colores extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad1U1
     */
    public Vista_Actividad_Colores() {
        initComponents();
    }

    public JTextField getAmarillo() {
        return amarillo;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public JLabel getjLabel2debeaparecer1() {
        return jLabel2debeaparecer1;
    }

    public JTextField getMorado() {
        return morado;
    }

    public JTextField getNaranja() {
        return naranja;
    }

    public JTextField getNaranjaz() {
        return naranjaz;
    }

    public JTextField getRojo() {
        return rojo;
    }

    public JTextField getVerde() {
        return verde;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2debeaparecer1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        amarillo = new javax.swing.JTextField();
        rojo = new javax.swing.JTextField();
        naranjaz = new javax.swing.JTextField();
        naranja = new javax.swing.JTextField();
        verde = new javax.swing.JTextField();
        morado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2debeaparecer1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2debeaparecer1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2debeaparecer1.setText("Escriba como los colores principales de estas frutas.");
        add(jLabel2debeaparecer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<html><center>COMPLETAR<br>ACTIVIDAD<center></html>");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 600, 180, -1));

        amarillo.setBackground(new java.awt.Color(227, 242, 253));
        amarillo.setForeground(new java.awt.Color(51, 51, 51));
        add(amarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 140, -1));

        rojo.setBackground(new java.awt.Color(227, 242, 253));
        rojo.setForeground(new java.awt.Color(51, 51, 51));
        add(rojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 140, -1));

        naranjaz.setBackground(new java.awt.Color(227, 242, 253));
        naranjaz.setForeground(new java.awt.Color(51, 51, 51));
        add(naranjaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, 140, -1));

        naranja.setBackground(new java.awt.Color(227, 242, 253));
        naranja.setForeground(new java.awt.Color(51, 51, 51));
        add(naranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 140, -1));

        verde.setBackground(new java.awt.Color(227, 242, 253));
        verde.setForeground(new java.awt.Color(51, 51, 51));
        add(verde, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, 140, -1));

        morado.setBackground(new java.awt.Color(227, 242, 253));
        morado.setForeground(new java.awt.Color(51, 51, 51));
        add(morado, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, 140, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lecciones/ActividadColores.jpg"))); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 900, 500));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lbl.jpg"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 660));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField amarillo;
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel2debeaparecer1;
    public javax.swing.JTextField morado;
    public javax.swing.JTextField naranja;
    public javax.swing.JTextField naranjaz;
    public javax.swing.JTextField rojo;
    public javax.swing.JTextField verde;
    // End of variables declaration//GEN-END:variables
}
