package VistasUnidad4;

import VistasUnidad3.*;
import Vista.*;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_Actividad_Vestimenta extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Actividad1U1
     */
    public Vista_Actividad_Vestimenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2debeaparecer1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2debeaparecer2 = new javax.swing.JLabel();
        Zapatos = new javax.swing.JTextField();
        Camiseta = new javax.swing.JTextField();
        Pantalon = new javax.swing.JTextField();
        Falda = new javax.swing.JTextField();
        Blusa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2debeaparecer1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2debeaparecer1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2debeaparecer1.setText("Escribe como son estas prendas en kiwcha");
        add(jLabel2debeaparecer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<html><center>COMPLETAR<br>ACTIVIDAD<center></html>");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 600, 180, -1));

        jLabel2debeaparecer2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2debeaparecer2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2debeaparecer2.setText("VESTIMENTA (CHURANAKUNA)");
        add(jLabel2debeaparecer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));
        add(Zapatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 170, 30));
        add(Camiseta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 170, 30));

        Pantalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantalonActionPerformed(evt);
            }
        });
        add(Pantalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 170, 30));
        add(Falda, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 170, 30));
        add(Blusa, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 170, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lecciones/actividad vestimenta.jpg"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 830, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void PantalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantalonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PantalonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Blusa;
    public javax.swing.JTextField Camiseta;
    public javax.swing.JTextField Falda;
    public javax.swing.JTextField Pantalon;
    public javax.swing.JTextField Zapatos;
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel2debeaparecer1;
    public javax.swing.JLabel jLabel2debeaparecer2;
    // End of variables declaration//GEN-END:variables
}
